### ISSUE TITLE
Exchange Stats

### ISSUE THREAD

**Issue by binelson** [kbudde/rabbitmq_exporter#10]
Would it be possible to add in exchange stats as gauge counters to this as well?  

eg: message_stats: {
publish: 0,
publish_details: {
rate: 0
},
publish_in: 5696,
publish_in_details: {
rate: 0
},
publish_out: 5696,
publish_out_details: {
rate: 0
},
ack: 0,
ack_details: {
rate: 0
},
deliver_get: 0,
deliver_get_details: {
rate: 0
},
confirm: 0,
confirm_details: {
rate: 0
},
return_unroutable: 0,
return_unroutable_details: {
rate: 0
},
redeliver: 0,
redeliver_details: {
rate: 0
}
},

I doubt the rate would be needed, since it can be calculated, but I would definitely find those stats useful as well.

**Comment by kbudde** [comment]
Hi,

I've checked it. It is possible. Pull Requests are always welcome :)

I will try it if I have a little bit more time.

BR

**Comment by binelson** [comment]
Sounds good. :)

I'm not a go expert which is why I put the request in initially, but if I get the gumption/time, I'll poke at it as well.

Thanks!
