### ISSUE TITLE
Messages time spent in queue

### ISSUE THREAD

**Issue by sylr** [kbudde/rabbitmq_exporter#100]
I don't know if it is feasible but I'd be really interested if this exporter could expose a summary or Histogram (I don't know which one is best suited) metric by queue which would track times that messages spend in queues before being delivered and acked.

**Comment by kbudde** [comment]
There is already one metric for queues:

| queue_head_message_timestamp | The timestamp property of the first message in the queue, if  present. Timestamps of messages only appear when they are in the  paged-in state. 
-- | --

It will not be possible to have the duration for each message inside the queue but it can be used to calculate the age for the first message inside the queue.

Please note there is also a plugin for rabbitmq to add the timestamp automatically:
rabbitmq_message_timestamp.
https://www.rabbitmq.com/community-plugins.html
