### ISSUE TITLE
Queue metrics are not exported

### ISSUE THREAD

**Issue by jralbert** [kbudde/rabbitmq_exporter#102]
On an installation polling a RabbitMQ 3.6.14 server, despite requesting it in the environment configuration, the "queue" and "exchange" metrics are not returned by the exporter. I'm specifying `RABBIT_EXPORTERS=exchange,node,overview,queue` and I get the overview and node metrics, but not the exchange or queue metrics.

**Comment by micemuni** [comment]
@jralbert  can you please send that rabbitmq json file.

**Comment by kbudde** [comment]
@jralbert do you still have issues?
If there are issues you should normally see something in the log of the exporter.

**Comment by jralbert** [comment]
@kbudde Yes, I've still got this issue. I turned logging up to the debug level, and I can see lines like these in the logs:

```Oct 29 19:45:03 galera201-utility-container-5a5708f0 rabbitmq_exporter[32470]: time="2018-10-29T19:45:03-07:00" level=debug msg="Metrics loaded" body="[]" endpoint=queues```

```Oct 29 19:45:03 galera201-utility-container-5a5708f0 rabbitmq_exporter[32470]: time="2018-10-29T19:45:03-07:00" level=debug msg="Queue data" queueData="[]"```

This suggests an empty metric set for the queues endpoint; similar lines are generated for "exchanges" and "overview" endpoints, but have a complex json object describing many metrics in their `body=` element.

There are no messages in the log at the warning level or above. Any advice on how I can get more details about why the exporter isn't traversing metrics for the queues endpoint? Thanks for your help on this.

**Comment by ananthrk** [comment]
@jralbert @kbudde Any updates on this please?

**Comment by kbudde** [comment]
@ananthrk How many queues and exchanges do you have?
Do you have any rabbitmq plugins active?
How is the exporter configured and how is prometheus scraping the data? 

The default timeout of 30s should be enough to handle many queues but perhaps it is too much.
But perhaps it is worth a try to increase the timeout value (RABBIT_TIMEOUT) to more than 30s.

**Comment by kbudde** [comment]
Can you call the api yourself /api/queues and check the response? It would be good if you can send me the results

**Comment by pascal08** [comment]
@jralbert What values do you see in Prometheus when you execute the metric `rabbit_module_up`?

I think we experience the same problem. Although I did not specify `RABBIT_EXPORTERS` as environment variable.

Here is the output of the `rabbit_module_up` metric in my case:

![selection_023](https://user-images.githubusercontent.com/5864409/52163288-3da0f800-26e0-11e9-924b-5acfb22ece6f.png)

The rest seems to be fine, since I can reach the exporter metric endpoint and the RabbitMQ management plugin from my Prometheus container.

**Comment by mKlaris** [comment]
Hi,

we have the same problem. Output of rabbit_module_up is 1 for every module.

But as you mentioned @kbudde above. I tried to call api /api/queues and I've got just header with 200 OK but no data. I also tried other api like /api/channels and there I can see header with data.

But, we are using RabbitMq for Openstack and we are using context Openstack. So maybe this is the problem.

**Comment by kbudde** [comment]
Hi, can check the rabbitmq.conf(ig). Perhaps there is a special configuration for the management plugin active.

**Comment by mKlaris** [comment]
Hi,

sorry for late reponse, we finally found the issue. Name of our vhost is "/openstack" and user guest hasn't permission for this api. 

We found:

> The vhost is a single segment. Therefore, any "/" characters that appear in the vhost name must be percent-encoded. URIs with multi-segment paths do not obey this specification.

So our right query for this api is:

`curl -i -u admin:XXXXX http://172.28.112.133:15672/api/queues/%2Fopenstack`

**Comment by kbudde** [comment]
Hi,

am I correct that the issue is just related to missing permissions for the monitoring user on the openstack vhost?
In this case we have a solution and the issue can be closed?
