### ISSUE TITLE
scrape time metric

### ISSUE THREAD

**Issue by jwalzer** [kbudde/rabbitmq_exporter#103]
Would it be possible, to export a metric on how long the scraping of the rabbitMQ took.

When setting up new Applications that use rabbit, and these are creating lots of new queues, it can happen, that the scraping takes a longer time.
Having Timing information can allow to monitor system (and monitoring) behaviour in deployment and rampup phases. Its hard to suddenly realize, that prometheus doesnt get any new metrics because the scraping times out, and I'd prefer to have an alerting before that happens.

**Comment by kbudde** [comment]
Prometheus is already creating such a metric:
scrape_duration_seconds

Is it enough for your needs or what else is needed?
