### ISSUE TITLE
Metrics are not coming to grafana

### ISSUE THREAD

**Issue by micemuni** [kbudde/rabbitmq_exporter#104]
Hi Team,
images used -> 
rabbitmq:3.7.8-management-alpine
prom/prometheus:v2.3.2
stefanprodan/swarmprom-grafana:5.0.1 

I have used this https://grafana.com/dashboards/4279 json file for rabbitmq but metrics are not coming 

**Note:-**  
    Here i got "Rabbitmq Monitoring" in grafana home page. If i click that no panels inside. 
Then one by one i have removed panel from json file, i got "node" panel only. but other panels are not coming. If i add other panel then No panels showing.

Not sure what is the issue. If metrics not coming then we need to check Prometheus, but here one panel are coming. 

I suspect that there is some syntax issue / expr error with that json file, Please suggest me to fix. 

Thank you in advance.

**Comment by micemuni** [comment]
Hi All,
Any update on this. ?

I could see the below plugins inside rabbitmq docker container. But still rabbitmq dashboard panels are not showing in Grafana board. 

/ # find /opt/rabbitmq/ -name "prometheus_*"
/opt/rabbitmq/plugins/prometheus_httpd-2.1.8.ez
/opt/rabbitmq/plugins/prometheus_rabbitmq_exporter-3.7.2.3.ez
/opt/rabbitmq/plugins/prometheus_cowboy-0.1.4.ez
/opt/rabbitmq/plugins/prometheus_process_collector-1.3.1.ez

**Comment by micemuni** [comment]
Hi All,
Below are the docker logs 

root@ip-10-85-0-239:~/Build_rabbitmq# docker logs cae5f3bf81889db9a0989d09db02e7c451305d4279598d93c307d24c556b856c
WARNING: Removing trailing slash from RABBITMQ_PLUGINS_EXPAND_DIR
WARNING: Removing trailing slash from RABBITMQ_PLUGINS_EXPAND_DIR
2018-10-31 09:37:47.669 [info] <0.33.0> Application lager started on node rabbit@cae5f3bf8188
2018-10-31 09:37:47.730 [error] <0.5.0>
Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 461
    rabbit:broker_start/0 line 335
    rabbit_plugins:setup/0 line 124
throw:{error,
          {cannot_delete_plugins_expand_dir,
              ["/opt/rabbitmq/plugins",
               {cannot_delete,"/opt/rabbitmq/plugins",eacces}]}}
Log file(s) (may contain more information):
   <stdout>

BOOT FAILED
===========

Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 461
    rabbit:broker_start/0 line 335
    rabbit_plugins:setup/0 line 124
throw:{error,
          {cannot_delete_plugins_expand_dir,
              ["/opt/rabbitmq/plugins",
               {cannot_delete,"/opt/rabbitmq/plugins",eacces}]}}
Log file(s) (may contain more information):
   <stdout>

Please let me how to fix this issue.

**Comment by kbudde** [comment]
Hi @micemuni ,

it looks like you are not using this exporter.
There are currently two exporters for rabbitmq:

1. The exporter from this repository is running as a separate application retrieving the metrics from the management plugin api interface.

2. The other exporter is running as plugin inside rabbitMQ: https://github.com/deadtrickster/prometheus_rabbitmq_exporter

From your second comment I see that you are using the plugin.
You should file your issue there. I'm closing this issue.

Best regards

Kris Budde
