### ISSUE TITLE
RabbitMQ HTTP API permissions issue

### ISSUE THREAD

**Issue by hedgepigdaniel** [kbudde/rabbitmq_exporter#107]
I had problems getting the exporter to work initially - I saw errors like this in the log:
```
Error while retrieving data from rabbitHost" error="<nil>" host="http://localhost:15672" statusCode=401
```

I fixed the issue by setting the `monitoring` tag on the rabbitmq user I had configured the exporter to use. (`rabbitmqctl set_user_tags <username> monitoring`)Perhaps it is worth mentioning in the README that this is required?

**Comment by alexdepalex** [comment]
Here the same with RabbitMQ version 3.4.4 (I know). It worked with 0.29.0. I did set the monitoring tag for that user, but didn't make any difference for me.

**Comment by asutosh24** [comment]
ime="2020-06-15T01:32:32Z" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="http://localhost:15672" statusCode=401

**Comment by mactanveer** [comment]
I am getting this error as well. Is this issue fixed yet @kbudde?

@hedgepigdaniel, how did you generate docker image with this fix?

**Comment by kbudde** [comment]
Hi,

The issue here were missing permission on rabbitmq.
If you are not using guest with localhost as url, you have to configure necessary rights for the user.

So in rabbit please add monitoring tag for the user and access to all monitored vhosts.
