### ISSUE TITLE
Queue-Limit as metric

### ISSUE THREAD

**Issue by julian-eggers** [kbudde/rabbitmq_exporter#108]
Hi,

it would be nice to have the queue-limit (x-max-length) as gauge-metric. 

Usage-example: Alert when the queue is over 90% full
CurrentSizeQueue > QueueLimit * 0.9

**Comment by kbudde** [comment]
Hi,

looks usefull and easy. I will add the metrics.

**Comment by kbudde** [comment]
It is included in the latest version of the docker image (v.1..WIP) and will be included in the next release.
