### ISSUE TITLE
Exporter is losing data from time to time

### ISSUE THREAD

**Issue by mfsimonbrz** [kbudde/rabbitmq_exporter#109]
Hi

I noticed that the data on Prometheus is missing some points.
This problem happens several times every day and started happening last week.
I run Prometheus v2.1.0 on Kubernetes and RabbitMQ Exporter as well.
I have a dashboard on Grafana with several alerts set and I had to turn them off because it was firing a lot.
I tried to delete the pod, in order to pull a newer image, but it had no effect.
I don't think it's an issue with the exporter itself, but I don't know what should I do to fix the problem.
Is there any configuration I can look in order to have the graphs without gaps again?
Here is a screenshot I took from my Prometheus.

![rabbitmq_exporter_failure](https://user-images.githubusercontent.com/16446746/49875644-a7033980-fe08-11e8-97b7-9da91acdac78.png)

Thank you.

**Comment by julian-eggers** [comment]
Please provide logfiles of the exporter or check if the exporter logs timeouts. I had the same problem and the solution was to increase the timeout for rabbitmq-scraping. 
The root problem was slow performance of the rabbitmq metric collection. Try to update to a new version or increase rabbitmq ressources.

**Comment by kbudde** [comment]
I'm closing this issue. If you still have issue more informations will be needed.

**Comment by kennyche** [comment]
Getting the same is as the above.  3.7.7 Rabbitmq, Prometheus 2.10.0, kbudde/exporter any of the v1.0 RCs.  If i roll back the exporter to 0.29.0 all is fine again.

Tried increasing the timeout to 60/120 seconds with the same results.  Can gladly post stdout logs, but no real errors that i can see.
