### ISSUE TITLE
rabbitmq3.2.2   Can I use exporter? 

### ISSUE THREAD

**Issue by jaxzhai** [kbudde/rabbitmq_exporter#111]
{"error":null,"host":"http://localhost:15672","level":"error","msg":"Error while retrieving data from rabbitHost","statusCode":406,"time":"2018-12-29T23:08:58+08:00"}
{"error":null,"host":"http://localhost:15672","level":"error","msg":"Error while retrieving data from rabbitHost","statusCode":406,"time":"2018-12-29T23:08:58+08:00"}
{"error":null,"host":"http://localhost:15672","level":"error","msg":"Error while retrieving data from rabbitHost","statusCode":406,"time":"2018-12-29T23:08:58+08:00"}
{"error":null,"host":"http://localhost:15672","level":"error","msg":"Error while retrieving data from rabbitHost","statusCode":406,"time":"2018-12-29T23:08:58+08:00"}

 Start command : RABBIT_USER=guest RABBIT_PASSWORD=guest OUTPUT_FORMAT=JSON PUBLISH_PORT=9099  RABBIT_URL=http://localhost:15672 nohup ./rabbitmq_exporter &
version: rabbitmq 3.2.2

**Comment by kbudde** [comment]
Hi,

RabbitMQ 3.2.2 is quite old. I cannot test it. I’m sorry I cannot give you any support on this. 
If you want to test it yourself. Pull requests are always welcome.
