### ISSUE TITLE
Arm64 builds

### ISSUE THREAD

**Issue by niedbalski** [kbudde/rabbitmq_exporter#112]
Hello,

Is there any limitation to implement arm64 support on the promu builds and releases?

Thanks!

**Comment by kbudde** [comment]
Hi,

I don’t see why it should not work. I can add an experimental build. So you can test it.

**Comment by niedbalski** [comment]
> Hi,
> 
> I don’t see why it should not work. I can add an experimental build. So you can test it.

Sure, @kbudde happy to test any build artifacts whenever you have them.

**Comment by kbudde** [comment]
Hi,

can you try this build?
It's based on the 1.0-beta branch. 
[rabbitmq_exporter-1.0.0-WIP.linux-arm64.tar.gz](https://github.com/kbudde/rabbitmq_exporter/files/2825279/rabbitmq_exporter-1.0.0-WIP.linux-arm64.tar.gz)
