### ISSUE TITLE
Release 1.0: grafana dashboard

### ISSUE THREAD

**Issue by kbudde** [kbudde/rabbitmq_exporter#114]
For release 1.0 we should have grafana dashboards showing all kind of important data.

As 1.0 implies a stability guarantee which is hard to define I would use this dashboard as reference. 
As long as the dashboards are working, the changes are note considered breaking. Version 1.x.

If the dashboards needs to be updated a new release should be created: 2.x.

Are there any good dashboards outside? What should be shown on the dashboard?

**Comment by Teriand** [comment]
![image](https://user-images.githubusercontent.com/26705069/53681856-5660f580-3d00-11e9-9be6-cd367dfb967b.png)

simple dashboard, base from https://grafana.com/dashboards/4279
Dashboard in release should be simple.

**Comment by c0psrul3** [comment]
I've created a revision of another RabbitMQ_Exporter dashboard, which works very well with helm-chart-installed "prometheus-rabbitmq-exporter".
https://github.com/c0psrul3/rabbitmq-exporter-dashboard-grafana

**Comment by c0psrul3** [comment]
> ![image](https://user-images.githubusercontent.com/26705069/53681856-5660f580-3d00-11e9-9be6-cd367dfb967b.png)
> 
> simple dashboard, base from https://grafana.com/dashboards/4279
> Dashboard in release should be simple.

@teriand , your dashboard works great, thank you for this!

**Comment by sshishov** [comment]
To tell in truth, I found this one is very nice, but unfortunately it will not work from the box for 0.29 and 1.0 releases if you have multi node cluster of RabbitMQ:
https://grafana.com/grafana/dashboards/10982

**Comment by elsgaard** [comment]
I am using this one: https://grafana.com/grafana/dashboards/4279 i had to tweaking it a little, but so far it is serving us well.

**Comment by kbudde** [comment]
Thank you for the examples
