### ISSUE TITLE
self label should be 1 for some node metrics

### ISSUE THREAD

**Issue by jbaumcloud** [kbudde/rabbitmq_exporter#117]
According to https://github.com/kbudde/rabbitmq_exporter/issues/92 series with `self="0"` should only contain info about other nodes than the node that was performing the scrape.

I have three RabbitMQ nodes, each of which has an exporter running as a sidecar. Since I am getting a lot of duplicate entries, I tried to drop all series that have `self="0"`. Now, I got rid of all duplicates for the queue module, but also dropped all series for the node module.

as an example:

```rabbitmq_fd_available{deployment="deployment1",exported_node="m1r1@m1r1",instance="int.m1r1.deployment.cloudandheat.com",job="rabbitmq-exporter",node="m1r1",rack="r000003",self="0"}```

Here `self` should be 1, since this is information about itself.

**Comment by jbaumcloud** [comment]
Thanks for the quick fix!

**Comment by kbudde** [comment]
You're welcome.

fix is included in 1.0 branch
