### ISSUE TITLE
metric idle_since is not exported.

### ISSUE THREAD

**Issue by kirancodify** [kbudde/rabbitmq_exporter#119]
I understand all the queue metrics are being queried. However, as part of the Queue metrics, idle_since is also a key in the json response. But this is not part of the metrics that are returned by the exporter. Can this be added as a metric ?

**Comment by kbudde** [comment]
I have to define the mapping. It should be easy.

**Comment by kirancodify** [comment]
Thanks that would be great.

**Comment by tommymonk** [comment]
Hi @kbudde any idea when a build including this will be ready ?
