### ISSUE TITLE
Mismatching docs between Docker Hub and Github

### ISSUE THREAD

**Issue by rojcosta** [kbudde/rabbitmq_exporter#124]
Hi,

After updating rabbitmq_exporter image I've realized the metric queuesTotal does not work anymore. Though it still listed on [Docker Hub](https://hub.docker.com/r/kbudde/rabbitmq-exporter) I've noticed it is not more documented on [Github page](https://github.com/kbudde/rabbitmq_exporter).

Could you update the Docker Hub page to match the same docs from Github? Another option is replace Docker Hub docs by one link to Github ones, this way you have a unique source of information.

**Comment by kbudde** [comment]
I've upgraded dockerhub now manually. I'll check if I can link them again.
