### ISSUE TITLE
Error while retrieving data from HTTPS rabbit host

### ISSUE THREAD

**Issue by bmarkons** [kbudde/rabbitmq_exporter#128]
Hi,

I am running the exporter in Kubernetes cluster.

However I am stuck with the following error:
```
level=error msg="Error while retrieving data from rabbitHost" error="Get <rabbit-url> x509: certificate signed by unknown authority" host="<host>" statusCode=0
```

Is there any trick which I might be missing in order to make exporter work with HTTPS Rabbit endpoint?

Thanks!

**Comment by kbudde** [comment]
Hi,

you have to provide the ertificate authority to the exporter. There is a setting for it: CAFILE. 
By default the exporter will use ca.pem in the same folder. For docker you need to mount the file inside the container.

There is also a less secure option to ignore certificate errors. Just set SKIPVERIFY=true. In this case all certificates are accepted.
