### ISSUE TITLE
How to build from source to modify config setting?

### ISSUE THREAD

**Issue by chithanh89** [kbudde/rabbitmq_exporter#129]
Hi guys,

Can someone tell me how to build from source to modify config setting?
Thanks and have a nice day.

**Comment by kbudde** [comment]
Hi,

it's a normal go application without much magic.
go get (go modules) will fetch all dependencies and go build will compile the application.
You can set some variables (e.g. Version) while compiling. I think the best example is the dockerfile where you can find all steps:
https://github.com/kbudde/rabbitmq_exporter/blob/master/Dockerfile#L31-L37

If you want to build your own docker image you can adjust the settings inside the dockerfile and run "docker -build -t myimage .".

**Comment by chithanh89** [comment]
Tks so much,i'm done.
