### ISSUE TITLE
Not using system trust roots

### ISSUE THREAD

**Issue by coderanger** [kbudde/rabbitmq_exporter#130]
I think in adding the custom CAFILE setting, you removed the loading of the system root certs. You copy over the root certs from the builder image so they are present, but you are using `x509.NewCertPool()` which creates a blank pool. I think maybe you meant to use `SystemCertPool`? That loads the default certs from /etc/ssl/certs but then you can add the CAFile cert if specified on top of that :)

**Comment by kbudde** [comment]
Fix was merged to master branch.
