### ISSUE TITLE
Scrape more RabbitMQ targets with one rabbitmq exporter

### ISSUE THREAD

**Issue by JaroVojtek** [kbudde/rabbitmq_exporter#134]
Is there an option to configure rabbitmq_exporter running in Kubernetes to scrape more than one RabbitMQ target host ?

Thank you

**Comment by xjantoth** [comment]
We would also appreciate if there would be an option to scrape n-rabbit instances. Thx

**Comment by kbudde** [comment]
You should always install one exporter per rabbitMQ.
I've started development to support the use case "one exporter per rabbitmq Cluster".  #131 

But it is not planned to support on exporter for more than one rabbitmq clusters.
