### ISSUE TITLE
Docker image ARM support 

### ISSUE THREAD

**Issue by winromulus** [kbudde/rabbitmq_exporter#138]
Hi,

Is there a limitation on running the exporter on ARM?
It would be great if a mixed-arch image would be built to support `arm` and `arm64` but I wanted to confirm that there's no architecture limitation.

**Comment by winromulus** [comment]
I've confirmed that this works on `arm`, but not with the images produced by the current build pipeline.
Since Docker requires an ARM daemon to pull and build the golang image, I've forked the project (no changes) and added an Azure Pipelines build configuration to it to build on one of our ARM agents.

The image repository: https://hub.docker.com/r/emberstack/rabbitmq-exporter

You can use `docker pull emberstack/rabbitmq-exporter:latest`  and docker will pull the correct image for `amd64` and `arm`.

@kbudde Let me know how you want to proceed with this. I would very much like to unify the build definitions to push to the original docker hub repository, but I don't think Travis has support for ARM agents.

For now we're using that image built from the Dockerfile in master (both on amd64 and arm)

**Comment by kbudde** [comment]
Hi,

I added github workflows to this project.
Docker images for arm are pushed to dockerhub now.

have fun
