### ISSUE TITLE
Need ability to configure TLS to skip certificate validation, or use custom CA

### ISSUE THREAD

**Issue by jcollie** [kbudde/rabbitmq_exporter#14]
I have a private CA that I use to sign certificates for RabbitMQ server and client use. The rabbitmq_exporter needs an option either to ignore certificate validation or to use a custom CA.

**Comment by kbudde** [comment]
Hi,
@jcollie  I will try to add the ability to use a custom ca. I think with Go 1.7 it is possible to load them at runtime.

**Comment by kbudde** [comment]
@jcollie I've added the option to add a ca during start of the exporter and the option to skip hostname and certificate check if needed.

The rabbitmq exporter is using the management plugin webinterface to read the data. I'm not sure if it is secured as well with the certificate. If it is it should be possible to get it running with the new options.

Can you please test it.
https://github.com/kbudde/rabbitmq_exporter/releases/tag/0.15-beta1
and give me some feedback.

**Comment by Laures** [comment]
i tried running the development tag (dockerhub) against cloudamqp with `-e SKIPVERIFY=1` and i still get: 

> Error while retrieving data from rabbitHost" error="Get https://hyena.rmq.cloudamqp.com/api/overview: x509: failed to load system roots and no roots provided

**Comment by kbudde** [comment]
@jcollie @Laures 
the branch was not merged to developed.
I've testest it with the hyena server. SKIPVERIFY=1 is working as expected.
