### ISSUE TITLE
Export only local metrics

### ISSUE THREAD

**Issue by Nyoroon** [kbudde/rabbitmq_exporter#146]
Hello!
I want to use rabbitmq_exporter as sidecar to every node in rabbitmq cluster and don't want to scrape duplicate metrics for each host.
Is it possible to scrape only local node metrics (and global ones if there's any)?

**Comment by MarcMielke** [comment]
We are running a 3 node (3 x sidecar) RMQ cluster in K8S and are getting confusing values like the following:
```
rabbitmq_connectionsTotal{cluster="rmq",endpoint="exporter",instance="100.103.0.2:9090",job="rabbitmq-ha",namespace="rabbitmq",pod="rabbitmq-ha-0",prometheus="monitoring/prometheus-operator-prometheus",service="rabbitmq-ha"} | 401
rabbitmq_connectionsTotal{cluster="rmq",endpoint="exporter",instance="100.104.0.2:9090",job="rabbitmq-ha",namespace="rabbitmq",pod="rabbitmq-ha-2",prometheus="monitoring/prometheus-operator-prometheus",service="rabbitmq-ha"} | 401
rabbitmq_connectionsTotal{cluster="rmq",endpoint="exporter",instance="100.127.0.2:9090",job="rabbitmq-ha",namespace="rabbitmq",pod="rabbitmq-ha-1",prometheus="monitoring/prometheus-operator-prometheus",service="rabbitmq-ha"} | 401
```

Each exporter returns the summed values for all RMQ nodes (correct values are 134,136,131). Exporter values should be node-scoped, right?

**Comment by Neki** [comment]
From what I can see by reading the code, this exporter directly returns the data reported by the RabbitMQ management API. The management API does collect cluster-wide statistics (assuming there are no network partitions) (reference: https://www.rabbitmq.com/clustering.html#clustering-and-observability).

Running this exporter as a sidecar on each node will result in collecting the same metrics several times, putting unnecessary load on the cluster. The RabbitMQ docs (linked above) recommend pointing observability tools at a load balancer in front of the cluster instead.

**Comment by MarcMielke** [comment]
great, that helps. thx!

**Comment by jerry8668** [comment]
Hi, I'm facing the same issue when I use AWS Network Load Balancer in front of RabbitMQ cluster (2 nodes).

If the metrics have a "self" label, they don't have duplicate data in Prometheus. But when I visualize dashboard in Grafana. It gets a different color in the graph.

Do you have any suggestions for this case?. Thanks
