### ISSUE TITLE
Add support for "MAX_QUEUES_PER_VHOST"

### ISSUE THREAD

**Issue by Neki** [kbudde/rabbitmq_exporter#147]
First, thanks for providing this exporter :slightly_smiling_face: 

I would be interested in having a "MAX_QUEUES_PER_VHOST" setting, that skip exporting queue data from vhosts with too many queues.
My use case is to have queue metrics for most vhosts, but protect Prometheus when there are too many queues in a given vhost (we have some applications that may suddenly create a lot of temporary queues).

For the record I don't think I'll have the time to provide a PR for this right now (this is more a "nice-to-have" than a "must-have", as I can also set a sample limit in Prometheus), but maybe this issue will give ideas to other people :sweat_smile:

**Comment by kbudde** [comment]
Hi,

there are already some other filters:
- you can limit the total number of Queues
- you can filter the queues by name

I would suggest to have some naming convention ( I know sometimes it's too late :) ) and filter out all temporary queues or just include the queues you want to monitor.

I would accept PR with MAX_QUEUES_PER_VHOST but I don't have the time to do it myself.
