### ISSUE TITLE
Doesn't Support Root Certificate from cloudAMQP

### ISSUE THREAD

**Issue by scott-kausler** [kbudde/rabbitmq_exporter#149]
rabbitmq_exporter gets an "x509: certificate signed by unknown authority" when connecting to CloudAMQP instances (hosted at *.rmq.cloudamqp.com).

This subdomain is signed using a Comodo root certifiate: https://www.cloudamqp.com/docs/faq.html

The correct root certificate can be downloaded from https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/979/108/domain-validation-sha-2

**Comment by kbudde** [comment]
Sysmte certificates were ignored in docker container until v1.0.0-RC7.
It should work now
