### ISSUE TITLE
rabbitmq_exporter error statuscode=500

### ISSUE THREAD

**Issue by vinodbadnal** [kbudde/rabbitmq_exporter#150]
Hi,

I have installed the rabbitmq_exporter on a linux server to scrape metrics from rabbitmq cluster but i see the following error in the logs.

Oct 11 14:04:23  rabbitmq_exporter: time="2019-10-11T14:04:23Z" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="" statusCode=500
Oct 11 14:04:23 rabbitmq_exporter: time="2019-10-11T14:04:23Z" level=warning msg="retrieving exchange failed" error="Error while retrieving data from rabbitHost"
Oct 11 14:04:23 rabbitmq_exporter: time="2019-10-11T14:04:23Z" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="" statusCode=500
Oct 11 14:04:23  rabbitmq_exporter: time="2019-10-11T14:04:23Z" level=warning msg="retrieving node failed" error="Error while retrieving data from rabbitHost"
Oct 11 14:04:24ce nrabbitmq_exporter: time="2019-10-11T14:04:24Z" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="" statusCode=500
Oct 11 14:04:24 rabbitmq_exporter: time="2019-10-11T14:04:24Z" level=warning msg="retrieving queue failed" error="Error while retrieving data from rabbitHost"
Oct 11 14:04:24 rabbitmq_exporter: time="2019-10-11T14:04:24Z" level=info msg="Metrics updated" duration=905.253101ms

I am able to get some of the metrics but not all of them.

**Comment by vinodbadnal** [comment]
Can someone have a fix for this error?

**Comment by caoxiaojian** [comment]
Check the username and password URL when you connect

**Comment by vinodbadnal** [comment]
> Check the username and password URL when you connect
The credentials seems fine as the exporter is able to get some of the metrics but not all of them.

**Comment by blackysy** [comment]
I same a problem.

**Comment by Yuanyp8** [comment]
I same a problem.

**Comment by Yuanyp8** [comment]
The same problem with me

**Comment by Yuanyp8** [comment]
any updates?

**Comment by Yuanyp8** [comment]
i have fix it 
use the  RABBIT_CAPABILITIES=bert

**Comment by vinodbadnal** [comment]
Hi,

I tried it and it worked perfectly. Thanks a lot for your help

Thanks,
Vinod badnal

**Comment by premkumarmkr** [comment]
> i have fix it
> use the RABBIT_CAPABILITIES=bert

i tried, it worked perfectly
