### ISSUE TITLE
Old metrics still exist

### ISSUE THREAD

**Issue by sssl93** [kbudde/rabbitmq_exporter#151]
Before scarping new metircs, didn't clean the old metrics, shall we call `Reset()` before  collect new

**Comment by dbevacqua** [comment]
We've observed something similar. Specifically with the following metrics, if the cluster name changes (which is a slightly weird situation, but could perhaps legitimately occur if scraping is attempted before the cluster has formed), values for the old cluster name remain:

- `rabbitmq_up`
- `rabbitmq_module_up`
- `rabbitmq_module_scrape_duration_seconds`

`Reset()` is indeed not called on these before `Collect()` (unlike with the `GaugeVec`s in e.g. `exporter_node.go`), so something as simple as the following (disclaimer: I haven't event attempted to compile this yet) may be all that's required.

```
diff --git a/exporter.go b/exporter.go
index 0c8b4e5..969b56b 100644
--- a/exporter.go
+++ b/exporter.go
@@ -101,6 +101,10 @@ func (e *exporter) Collect(ch chan<- prometheus.Metric) {
 
        BuildInfo.Collect(ch)
 
+ e.upMetric.Reset()
+ e.endpointUpMetric.Reset()
+ e.endpointScrapeDurationMetric.Reset()
+
        if allUp {
                e.upMetric.WithLabelValues(e.overviewExporter.NodeInfo().ClusterName, e.overviewExporter.NodeInfo().Node).Set(1)
        } else {
```

**Comment by kremius** [comment]
In our case we sometimes observe stale `rabbitmq_up{cluster="",node=""} 0` metric (`kbudde/rabbitmq-exporter:v1.0.0-RC6.1` image).

**Comment by OfficerKoo** [comment]
What's the status of this? We have Jenkins job that rotates our rabbitMQ nodes, after each rotation nodes ip changes and we have old metrics in exporter. Exporter restart fixes the problem, but it is not desirable workaround

**Comment by kbudde** [comment]
Included in RC8
