### ISSUE TITLE
 (http.go:306)

### ISSUE THREAD

**Issue by AlanQin1024** [kbudde/rabbitmq_exporter#153]
{"duration":10591217533,"level":"info","msg":"Metrics updated","time":"2019-10-30T11:27:13+08:00"}
2019/10/30 11:27:13 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)

**Comment by kbudde** [comment]
Hi,
can you please give me some information about this issue:
- Which version of exporter and rabbitmq are you using
- operating system / deployed with docker
- is it a direct connection from export to rabbitmq or is a proxy/lb involved?
