### ISSUE TITLE
Comparison with official RabbitMQ exporter (3.8)

### ISSUE THREAD

**Issue by rgarrigue** [kbudde/rabbitmq_exporter#156]
Hi

Seems RabbitMQ now ships [their own exporter](https://www.rabbitmq.com/prometheus.html). Can you explain add a comparison in the README to help people choose between the two ? 

Best regards,

**Comment by shamil** [comment]
From my experience official Prometheus plugin lacks some features this exporter provides, specifically ability to skip collecting some metrics. In official plugin you have 2 choices either aggregated metrics or per-object, and no option to skip unwanted metrics.

On the other hand, official plugin provides `erlang` VM metrics, which is important as well. So I use them both. In official plugin I've disabled `per-object` metrics and use it only to collect `erlang` related metrics, for everything else I use this exporter.

Hope this helps.

**Comment by mkuratczyk** [comment]
In recent RabbitMQ versions, the native Prometheus plugin provides another endpoint: `/metrics/detailed`. It allows to explicitly query only selected metrics from selected vhosts:
https://github.com/rabbitmq/rabbitmq-server/tree/master/deps/rabbitmq_prometheus#selective-querying-of-per-object-metrics
