### ISSUE TITLE
How to generate msi file for windows

### ISSUE THREAD

**Issue by khadar-sk** [kbudde/rabbitmq_exporter#158]
Please provide the steps to how to build the msi file for windows. or Can we use sc.exec in powershell to create and remove to run as a service in windows. Please share any other way how to do that

**Comment by kbudde** [comment]
Hi,

I've never tried to generate msi for rabbitmq_exporter. sc.exe could work but I've never tested it.
Normally I'm using wrapper https://nssm.cc/ for creating services.
