### ISSUE TITLE
"invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by Vannevelj** [kbudde/rabbitmq_exporter#16]
I've cloned your repo, built the source and configured everything. When I run the exe it gives me the default Go metrics but none of the Rabbit specific stuff.
Lots of error messages saying 

> "Error while decoding json"
> "invalid character '<' looking for beginning of value

![image](https://cloud.githubusercontent.com/assets/2777107/18584949/f85a6c6c-7c0b-11e6-9dbd-14010158f7cf.png)

The bottom of the response contains this:

![image](https://cloud.githubusercontent.com/assets/2777107/18584974/26d468ea-7c0c-11e6-91c5-450cdbca53b5.png)

We run RabbitMQ 3.5.5

Any idea as to what might be wrong?

**Comment by kbudde** [comment]
Hi,

RabbitMQ 3.5.5 should work.
The error message means that the json response of the rabbitmq management plugin is invalid.

Can you please post the response of http://rabbitmq:15672/api/overview.
It should be valid json and not contain something like "key":**<**"value".

**Comment by Vannevelj** [comment]
This is the response I receive which seems to be valid json:

```
{"management_version":"3.5.5","rates_mode":"basic","exchange_types":[{"name":"topic","description":"AMQP topic exchange, as per the AMQP specification","enabled":true},{"name":"x-delayed-message","description":"Delayed Message Exchange.","enabled":true},{"name":"fanout","description":"AMQP fanout exchange, as per the AMQP specification","enabled":true},{"name":"direct","description":"AMQP direct exchange, as per the AMQP specification","enabled":true},{"name":"headers","description":"AMQP headers exchange, as per the AMQP specification","enabled":true}],"rabbitmq_version":"3.5.5","cluster_name":"rabbit@590411-app1.viagogors.prod","erlang_version":"17.3","erlang_full_version":"Erlang/OTP 17 [erts-6.2] [64-bit] [smp:24:24] [async-threads:30]","message_stats":{"publish":195411184,"publish_details":{"rate":1513.0},"ack":207683485,"ack_details":{"rate":1308.2},"deliver_get":259852208,"deliver_get_details":{"rate":1310.8},"redeliver":52073023,"redeliver_details":{"rate":0.0},"deliver":259757418,"deliver_details":{"rate":1310.4},"get_no_ack":94790,"get_no_ack_details":{"rate":0.4}},"queue_totals":{"messages":106858,"messages_details":{"rate":235.6},"messages_ready":106551,"messages_ready_details":{"rate":233.2},"messages_unacknowledged":307,"messages_unacknowledged_details":{"rate":2.4}},"object_totals":{"consumers":232,"queues":223,"exchanges":69,"connections":450,"channels":415},"statistics_db_event_queue":0,"node":"rabbit@804970-APP1","statistics_db_node":"rabbit@804970-APP1","listeners":[{"node":"rabbit@804970-APP1","protocol":"amqp","ip_address":"0.0.0.0","port":5672},{"node":"rabbit@804970-APP1","protocol":"amqp","ip_address":"::","port":5672},{"node":"rabbit@804971-APP2","protocol":"amqp","ip_address":"0.0.0.0","port":5672},{"node":"rabbit@804971-APP2","protocol":"amqp","ip_address":"::","port":5672},{"node":"rabbit@590411-APP1","protocol":"clustering","ip_address":"::","port":25672},{"node":"rabbit@804970-APP1","protocol":"clustering","ip_address":"::","port":25672},{"node":"rabbit@804971-APP2","protocol":"clustering","ip_address":"::","port":25672}],"contexts":[{"node":"rabbit@804970-APP1","description":"RabbitMQ Management","path":"/","port":"15672"},{"node":"rabbit@804971-APP2","description":"RabbitMQ Management","path":"/","port":"15672"}]}
```

**Comment by kbudde** [comment]
@Vannevelj you are right this is valid json and it will work. I suspect the rabbitmq exporter gets a different response. 
Can you please compile the develop branch and run the exporter with LOG_LEVEL=DEBUG. It will show the rabbitmq response before decoding.
Just to be sure the RABBIT_URL should be http://HOST:PORT without trailing "/" or path.

**Comment by Vannevelj** [comment]
Ah, silly mistake from my part. I had `/#/` appended at the end which blew things up. Looks like everything is working great! The response time didn't seem very fluent but that might be because I was testing it over vpn and there's a LOT of metrics to be aggregated in our setup. I'll look into that closer on Monday but everything here is resolved.

Thanks for the help! I look forward to putting your exporter to good use.
