### ISSUE TITLE
rabbitmq_exporter error statuscode=0

### ISSUE THREAD

**Issue by hejianle** [kbudde/rabbitmq_exporter#160]
Hi @kbudde , When I used rabbitmq_exporter I have the following problems：
![image](https://user-images.githubusercontent.com/12504927/75335624-badb7400-58c4-11ea-8973-0e654b2422b6.png)
What does the statusCode=0 mean? What can I do to solve this problem?Thanks for  your help to solve this problem.

**Comment by kbudde** [comment]
Hi,

The exporter needs to access rabbit management api (port 15672).
Regarding to your logs you configured rabbit amqp port (port 5672).
BR
