### ISSUE TITLE
RabbitMQ exporter doesn't load configuration from config file

### ISSUE THREAD

**Issue by liortzur-fiverr** [kbudde/rabbitmq_exporter#161]
RabbitMQ exporter seem to have a bug makes it be unable to load configuration when use a json config file.
Example:
Config file created in /etc/rabbitmq_exporter_main.json:
```
{"max_queues":0,"output_format":"TTY","publish_addr":"127.0.0.1","publish_port":9419,"rabbit_capabilities":"nobert","enabled_exporters":["exchange","node","overview","queue"],"timeout":30,"rabbit_url":"http://127.0.0.1:15672","insecure_skip_verify":false}
```
Actual configuration loaded by the exporter:
```
BRANCH=heads/v1.0.0-RC6.1 BUILD_DATE="20190426-18:57:58" REVISION=6db8c3822c77b6577b39e6d5a1868c6c5a28dfe2 VERSION=1.0.0-RC6.1
INFO[0000] Active Configuration
CAFILE=ca.pem EXCLUDE_METRICS="[]" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=9419 RABBIT_CAPABILITIES="bert,no_sort" RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=30 RABBIT_URL="http://127.0.0.1:15672" RABBIT_USER=guest SKIPVERIFY=false SKIP_QUEUES="^$" SKIP_VHOST="^$"
```
Note the setting of rabbit_capabilities wasn't loaded by the rabbitmq exporter.

**Comment by padraiglennon** [comment]
I've had the same issue

**Comment by jawr** [comment]
ditto

**Comment by Jobjik** [comment]
+1
/etc/rabbitmq_exporter/config.json
/etc/rabbitmq_exporter/rabbitmq.conf
./conf/rabbitmq.conf
-config-file or --config-file
not working

**Comment by iamxaero** [comment]
+

**Comment by gondaz** [comment]
+1

**Comment by kbudde** [comment]
Hi,

conf/rabbitmq.conf is the default path. If a config file is found it will be used.

You can overwrite default with:
- "--config-file .\config.example.json"
- "-config-file .\config.example.json"

There was no released version with config file support. It was only available on docker latest.
Please check latest release v1.0.0-RC7. It's included now.

**Comment by padraiglennon** [comment]
Hi. That change is working for me. Thanks for the quick turnaround on this

**Comment by howiezhao** [comment]
I have encountered the same problem, finally it was found that the configuration file was written incorrectly, the configuration in `rabbitmq.conf` is:

```json
{
    "rabbit_capabilities": "nobert"
}
```

It is not right to write like this, the configuration file should be written in full as in the example, hope to give the later some reference.
