### ISSUE TITLE
Queue and connection metrics per cluster member

### ISSUE THREAD

**Issue by vinodbadnal** [kbudde/rabbitmq_exporter#162]
Hi,

I have setup this exporter and i am able to generate all the metrics but they are for the overrall cluster.
I have a cluster of 3 nodes and i would like to measure specific metrics like queue, connection metrics based on an indiviual node.

Is it possible to do it using this exporter.

Thanks,
Vinod Badnal

**Comment by kbudde** [comment]
There is a label for most of the metrics: "self". If self==1 the queue resides primary on this node.
