### ISSUE TITLE
RC7 docker image lacks RC7 tags

### ISSUE THREAD

**Issue by daghb** [kbudde/rabbitmq_exporter#164]
Seems like the lates image on Docker Hub is "latest" with no version tag.

**Comment by shamil** [comment]
Yeah @kbudde can you please push the tag?

**Comment by kbudde** [comment]
Travis build was broken.
I've reactivated dockerhub builds for the moment. Tag v.1.0.0-RC7.1 is the same as v.1.0.0-RC7.
