### ISSUE TITLE
[BUG] idle_since never resets

### ISSUE THREAD

**Issue by gaizeror** [kbudde/rabbitmq_exporter#165]
As you can see, the idle_since gauge never resets, it acts more like a counter
<img width="1428" alt="Screen_Shot_2020-05-04_at_18_17_28" src="https://user-images.githubusercontent.com/18627927/80982275-c783c780-8e33-11ea-83b0-c3db66b1bb54.png">

**Comment by zerkms** [comment]
If it's `idle_since` - then it should export the last timestamp it was idle _since_. Semantics of _since_ expresses "point in time/instant".

Your change in turn makes it `idle_for`, and the semantics would be "duration".

**Comment by kbudde** [comment]
@gaizeror I agree with @zerkms your change is changing semantics of the metric itself.

Maybe you can tell us more about your use case. I don't have any idle queues, so I'm missing the use case.

I would try to calculate duration like this:

    time() - rabbitmq_queue_idle_since_seconds{queue="foo"}
