### ISSUE TITLE
vhost permissions for the monitor user? 

### ISSUE THREAD

**Issue by ccp-codex** [kbudde/rabbitmq_exporter#167]
Does the monitor user require read permissions on each vhost we care about? 

If there's documentation (or code) that would let me understand the permission requirements for the monitoring user I'd love to have a reference to it to better understand this topic. 

Thanks in advance!

**Comment by kbudde** [comment]
Hi,

yes, the user used to monitor rabbitmq needs monitoring rights on **all** vhosts.
This exporter queries API of rabbitmq management plugin to retrieve the data.

Therefore you can find the details there: https://www.rabbitmq.com/management.html#permissions
