### ISSUE TITLE
v1.0.0-RC7.1 RabbitMQ exporter doesn't load configuration from config file

### ISSUE THREAD

**Issue by zhagyilig** [kbudde/rabbitmq_exporter#168]
version: v1.0.0-RC7.1 , RabbitMQ exporter doesn't load configuration from config file
but, v1.0.0-RC7 is running

**Comment by te4336** [comment]
Any progress on this??

**Comment by kbudde** [comment]
Hi,

can you please give me some more  information on how you try to load config file?
Please post how you are starting the exporter (flags, config file location) and start up logs.

I've noticed a bad default for config file name: confg/rabbitmq.conf
So, you should pass flag to exporter, e.g. `rabbitmq_exporter -config-file myconf.json`
