### ISSUE TITLE
grafana show no data

### ISSUE THREAD

**Issue by lz71** [kbudde/rabbitmq_exporter#169]
Grafana v6.7.3
prometheus V2.18.1
rabbitmq_exporter 1.0.0-RC7
conf：
![image](https://user-images.githubusercontent.com/66774710/89517748-c1273200-d80c-11ea-9ed4-c0dab66b2472.png)
prometheus ---The node is in good health
![image](https://user-images.githubusercontent.com/66774710/89518061-fdf32900-d80c-11ea-9a7a-dbc0c43c399c.png)
Grafana---Why is there no data
![image](https://user-images.githubusercontent.com/66774710/89518243-38f55c80-d80d-11ea-9242-04d97ef753c2.png)
Looking forward to your reply. Thank you

**Comment by kbudde** [comment]
I don't know which grafana dashboard you are using.
Maybe this dashboard uses job name as filter or some other filter.

Please edit one widget and check the query. I suspect it includes something like job="rabbitmq_exporter".
Then you would have to edit the dashboard to match your job name or the other way around.

BR

Kris

**Comment by lz71** [comment]
@kbudde   Thank you for your answer, but I am a tester and will not modify it. May I ask which template you suggest to use

**Comment by lz71** [comment]
@kbudde 
![image](https://user-images.githubusercontent.com/66774710/89705499-7d5d3580-d990-11ea-93f6-35f925badf50.png)
Hello, in Promethaus, I found some indicators with data and some showed No Datapoints found. I don't know why this happened.Thank you for your answer. In addition, the account authority configured in the configuration file is Administrator

**Comment by kbudde** [comment]
Hi,

using prometheus to find the issue sounds like a good idea.
First of all which rabbitmq version are you using? maybe you can get the data from prometheus: "rabbitmq_version_info"
If this failes you will probably have a version older than 3.6.9 (see https://github.com/kbudde/rabbitmq_exporter#extended-rabbitmq-capabilities for workaround: nobert)

if your rabbitmq is up2date it should work if the account has correct rights. Btw. the user only needs monitoring role on all vhosts
Can you check these in prometheus?
- rabbitmq_queues
- count(rabbitmq_queue_messages) by (job)
- rabbitmq_module_up
