### ISSUE TITLE
rabbitmq_up with empty labels

### ISSUE THREAD

**Issue by pezzak** [kbudde/rabbitmq_exporter#171]
If exporter was started before rabbitmq-server, then there will be the **rabbitmq_up** metric with empty labels. And if rabbitmq-server started after that, this metric will be saved:

```
# HELP rabbitmq_up Was the last scrape of rabbitmq successful.
# TYPE rabbitmq_up gauge
rabbitmq_up{cluster="",node=""} 0
```

```
# HELP rabbitmq_up Was the last scrape of rabbitmq successful.
# TYPE rabbitmq_up gauge
rabbitmq_up{cluster="",node=""} 0
rabbitmq_up{cluster="rabbit@some.host.local",node="rabbit@some.host.local"} 1
```

**Comment by petrsp** [comment]
Is there a chance that you merge PR #172? We have the same issue. We use a docker container in Docker Swarm.

**Comment by kbudde** [comment]
Included in RC8
