### ISSUE TITLE
lack of some metrics 

### ISSUE THREAD

**Issue by wenjun8888** [kbudde/rabbitmq_exporter#174]
hey:
i use version 0.29 with an administrator.
but i find there is only fews metircs find，which are：
![image](https://user-images.githubusercontent.com/23557780/92697334-c6344f80-f37d-11ea-8d94-b67a985b3f83.png)

how can i get all metircs?
thank you!

**Comment by kbudde** [comment]
Hi,

please use the latest version. It's always to easier if we don't need to go back two years.

Please post:
- rabbitmq version
- exporter configuration
- exporter log
