### ISSUE TITLE
Metric to show SSL or non-SSL connections

### ISSUE THREAD

**Issue by sheiks** [kbudde/rabbitmq_exporter#176]
It's good to show a metric whether connection is SSL or non-SSL which is currently not available in this exporter.

**Comment by kbudde** [comment]
Hello,

I'm generally biased about connection metrics. There can be frequent changes here and the significance to gather metrics is minimal.
The number of connection with/without SSL is more a snapshot than a metric. 
It is currently not planned to include metrics for encryption status.
