### ISSUE TITLE
rabbitmq_federation_state metric always exposing 1 as value

### ISSUE THREAD

**Issue by bilalcaliskan** [kbudde/rabbitmq_exporter#179]
Hello,

`rabbitmq_federation_state` metric always exposing 1 as value.

https://github.com/kbudde/rabbitmq_exporter/blob/main/exporter_federation.go#L50

**Comment by kbudde** [comment]
Hello,

this is by intention. The label "status" changes depending on the status of your federation. 
This way you can count the number of running federation links: ```sum(rabbitmq_federation_state{status="running"})```

I think It would be better to preinitialise all possible status fields for this metric (all with value 0 except the current status 1)
