### ISSUE TITLE
Node statistics

### ISSUE THREAD

**Issue by nvx** [kbudde/rabbitmq_exporter#18]
Per-node statistics (memory, disk space, etc) would be a useful addition to this. I believe this information comes from hitting /api/nodes

**Comment by kbudde** [comment]
Hi,

you are right. There are some interesting statistics. 
I will add it to the next release. Or are you interested in doing it yourself?

Is there something special you want to see?

**Comment by nvx** [comment]
Nothing overly special, just noticed it missing.

Given enough time I'd probably implement it myself, but in the shorter term I can't see myself getting around to it unfortunately.
