### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by uglyliu** [kbudde/rabbitmq_exporter#181]
I run the program,and can get data,but the log is the following

time="2021-02-04T17:52:36+08:00" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="http://172.18.103.58:15672" statusCode=401

**Comment by kbudde** [comment]
There is some information missing about how the exporter and RabbitMQ were installed.

If I had to guess, I would say that both started in separate containers / with different IPs.

RabbitMQ then does not allow access with the loopback user "guest" in this case. I recommend creating a user / password in your RabbitMQ cluster(?) with monitoring role and access to all vhosts. This should work.
