### ISSUE TITLE
Flag provided but not defined

### ISSUE THREAD

**Issue by BC-VadymZ** [kbudde/rabbitmq_exporter#188]
Version 1.0.0~rc6.1-1 starts from the command line with the flags:
```
/usr/bin/prometheus-rabbitmq-exporter --web.listen-address=0.0.0.0:9419 --web.telemetry-path=/metrics
INFO[0000] Using default certificate pool
INFO[0000] Starting RabbitMQ exporter                    BRANCH=heads/v1.0.0-RC6.1 BUILD_DATE="20190426-18:57:58" REVISION=6db8c3822c77b6577b39e6d5a1868c6c5a28dfe2 VERSION=1.0.0-RC6.1
INFO[0000] Active Configuration                          CAFILE=ca.pem EXCLUDE_METRICS="[]" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=9419 RABBIT_CAPABILITIES="no_sort,bert" RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=30 RABBIT_URL="http://127.0.0.1:15672" RABBIT_USER=guest SKIPVERIFY=false SKIP_QUEUES="^$" SKIP_VHOST="^$"
```
version 1.0.0~rc8-1 does not:
```
/usr/bin/prometheus-rabbitmq-exporter --web.listen-address=0.0.0.0:9419 --web.telemetry-path=/metrics
flag provided but not defined: -web.listen-address
Usage of /usr/bin/prometheus-rabbitmq-exporter:
  -check-url string
    	Curl url and return exit code (http: 200 => 0, otherwise 1)
  -config-file string
    	path to json config (default "conf/rabbitmq.conf")
```
how I can pass arguments in the command line without using conf file?

**Comment by kbudde** [comment]
Commandline arguments were never implemented.

You can set configure all settings with environment variables or inside configuration file. I hope this helps.

> PUBLISH_PORT=1234 ./rabbitmq_exporter
INFO[0000] Using default certificate pool               
INFO[0000] Starting RabbitMQ exporter                    BRANCH=heads/v1.0.0-RC6.1 BUILD_DATE="20190426-18:57:58" REVISION=6db8c3822c77b6577b39e6d5a1868c6c5a28dfe2 VERSION=1.0.0-RC6.1
INFO[0000] Active Configuration                          CAFILE=ca.pem EXCLUDE_METRICS="[]" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=1234 RABBIT_CAPABILITIES="no_sort,bert" RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=30 RABBIT_URL="http://127.0.0.1:15672" RABBIT_USER=guest SKIPVERIFY=false SKIP_QUEUES="^$" SKIP_VHOST="^$"
