### ISSUE TITLE
how to use `EXCLUDE_METRICS` 

### ISSUE THREAD

**Issue by LiYiPeng-1** [kbudde/rabbitmq_exporter#211]
hi, I have a question, how to use `EXCLUDE_METRICS` , when  I  set  `"exlude_metrics": [rabbitmq_queue_idle_since_seconds]` or `"exlude_metrics": [idleSinceMetric]`, It doesn't work ，this indicator can still be collected  ,`rabbitmq_queue_state` is  the  same 
 ,  how  can I  exclude  this  Metric   `rabbitmq_queue_idle_since_seconds`     and  `rabbitmq_queue_state`     (my  rabbitmq  version is 3.6.5  , rabbitmq-exporter  version is  latest)   @kbudde

**Comment by LiYiPeng-1** [comment]
my config about  EXCLUDE_METRICS 
`
"exlude_metrics":[idleSinceMetric,disk_reads,disk_writes,garbage_collection.fullsweep_after,garbage_collection.min_bin_vheap_size,garbage_collection.min_heap_size,garbage_collection.minor_gcs,idleSinceMetric,memory,message_bytes_ram,message_stats.ack,message_stats.confirm,message_stats.deliver_no_ack,message_stats.get_no_ack,message_stats.get,messages_persistent,messages_published_total,messages_ram,messages_ready_ram,message_stats.redeliver,message_stats.return,messages_unacknowledged_ram,reductions,stateMetric]
`

**Comment by kbudde** [comment]
Hi @LiYiPeng-1 ,

the filtering of the metrics has a quite bad user experience. You've used the correct filtering so far

e.g. "message_stats.return" removes the metrics "queue_messages_returned_total" 
You can find the mapping for the example here: https://github.com/kbudde/rabbitmq_exporter/blob/f3746082e44ac6fd3b497a8f4978c4a97e110780/exporter_queue.go#L56

I think you were able to figure this out already.

For the metrics "rabbitmq_queue_idle_since_seconds" and "rabbitmq_queue_state" I fear it is currently not possible to filter them out with configuration of the exporter as they are implemented differently.

**Comment by LiYiPeng-1** [comment]
> Hi @LiYiPeng-1 ,
> 
> the filtering of the metrics has a quite bad user experience. You've used the correct filtering so far
> 
> e.g. "message_stats.return" removes the metrics "queue_messages_returned_total"
> You can find the mapping for the example here:
> 
> https://github.com/kbudde/rabbitmq_exporter/blob/f3746082e44ac6fd3b497a8f4978c4a97e110780/exporter_queue.go#L56
> 
> I think you were able to figure this out already.
> 
> For the metrics `rabbitmq_queue_idle_since_seconds` and `rabbitmq_queue_state` I fear it is currently not possible to filter them out with configuration of the exporter as they are implemented differently.

oh，Thank you for your reply ，at first it was difficult to understand how to use it
