### ISSUE TITLE
Setings INCLUDE_QUEUES

### ISSUE THREAD

**Issue by Pekto1** [kbudde/rabbitmq_exporter#223]
It would be nice if you could specify the queues you want to monitor after a comma or other character in addition to using regex .

**Comment by kbudde** [comment]
Hi,

sorry for the late reply. you can archieve the same with regex and it's not really complex.
So instead of writing 

    INCLUDE_QUEUES="my_queue,anotherqueue"

you can write

    INCLUDE_QUEUES="^(my_queue|anotherqueue)$"

If all your important queues have the suffix queue, you can even save some letters

    INCLUDE_QUEUES="^(my_|another)queue$"

**Comment by Pekto1** [comment]
Is it possible to combine the above and to sum the queues e.g. with the prefix "_slow"
