### ISSUE TITLE
Feature: RABBITMQ_CONNECTION  mode: loadbalancer

### ISSUE THREAD

**Issue by kbudde** [kbudde/rabbitmq_exporter#230]
At the moment it is recommended to install one exporter per rabbitmq without any loadbalancer in between.

Another option would be to run a loadbalancer between the exporter and the rabbitmq cluster.
one exporter -> loadbalancer -> rabbitmq cluster

The second option is currently not supported but normally used for installations in k8s. As a result the graphs in prometheus will have gaps (see #131 ). These gaps are caused by the self label which is added to nodes, exchanges, etc..
So it would be quite useful to add configuration option to prevent adding this label from all metrics: 

`RABBITMQ_CONNECTION` with to options: `direct` (default) or `loadbalancer`

- `direct`: self label is added to the metrics ( as now)
- `loadbalancer`: self label is removed from all metrics

**Comment by kotyara85** [comment]
The native plug-in doesn’t have federation. 
thanks for the explanation, I will give it a shot!

**Comment by marek-obuchowicz** [comment]
:+1: - we're using this exporter to monitor rabbitmq clusters not running in k8s - they run on AWS autoscaling groups with loadbalancer in front.

**Comment by kbudde** [comment]
Implemented in https://github.com/kbudde/rabbitmq_exporter/releases/tag/v1.0.0-RC19
