### ISSUE TITLE
How to use with rmq operator

### ISSUE THREAD

**Issue by kotyara85** [kbudde/rabbitmq_exporter#237]
Hi @kbudde ,
Is there any docs how to use this with official k8s operator?
I do have a stateful set running.
Need to export federation status
Thanks

**Comment by kbudde** [comment]
Hi @kotyara85,
I've never used it with the official exporter but I can give you some hints:
- At the moment this exporter expects a direct connection to one rabbitmq server. 
  - You must install one exporter per member of the statefulset. 
- Alternatively you can install one exporter and point it to svc/rabbitmq-server BUT in this case you need  to drop the self label. See https://github.com/kbudde/rabbitmq_exporter/issues/131#issuecomment-547778747.
This is necessary until #230 is implemented.
- Last but not least RabbitMQ 3.8 has a native prometheus plugin. Mabye it fits your needs as well.

BR
