### ISSUE TITLE
params  "include_queues" and "skip_queues" not work

### ISSUE THREAD

**Issue by feixiangingk** [kbudde/rabbitmq_exporter#245]
i  set params like this {    "include_queues":"m.*","skip_queues": "pythonTest",...},run rabbitmq_exporter and get log:
{"CAFILE":"","CERTFILE":"","EXCLUDE_METRICS":null,"INCLUDE_QUEUES":{},"INCLUDE_VHOST":{},"KEYFILE":"","MAX_QUEUES":0,"OUTPUT_FORMAT":"JSON","PUBLISH_ADDR":"","PUBLISH_PORT":"9419","RABBIT_CAPABILITIES":"","RABBIT_EXPORTERS":["exchange","node","overview","queue"],"RABBIT_TIMEOUT":25,"RABBIT_URL":"http://127.0.0.1:15672","RABBIT_USER":"admin","SKIPVERIFY":false,"SKIP_QUEUES":"pythonTest","SKIP_VHOST":"","level":"info","msg":"Active Configuration","time":"2021-12-26T02:27:44+08:00"}

but,in prometheus,i query "rabbitmq_queue_messages_ready",i find this metric include all queues

**Comment by kbudde** [comment]
The configuration and the log output don't match. Include_queues is set to "m.*" but it starts with setting `{}`. This is quite strange.
Which version (exporter and rabbitmq) do you use?

**Comment by feixiangingk** [comment]
rabbitmq run in docker,tag is "3.8.9-management" ,scripts is "docker run -d -it --name rabbitmq -p 5672:5672 -p 15672:15672 -p 15692:15692 -e RABBITMQ_DEFAULT_USER=admin -e RABBITMQ_DEFAULT_PASS=123456  --hostname rabbitmq rabbitmq:3.8.9-management"

the exporter version is "rabbitmq_exporter-1.0.0-RC8.linux-amd64.tar.gz" ,i run with config file:
{
    "rabbit_url": "http://127.0.0.1:15672",
    "rabbit_user": "admin",
    "rabbit_pass": "123456",
    "publish_port": "9419",
    "output_format": "JSON",
    "insecure_skip_verify":false,
    "include_queues":"m.*",
    "skip_queues": "pythonTest",
    "enabled_exporters": [
            "exchange",
            "node",
            "overview",
            "queue"
    ],
    "timeout": 25
}

**Comment by kbudde** [comment]
Hi,
first of all you have must set all values with configuration file. There are no defaults while using the config file option..
But this still does not explain why the filters are not working in your case. I would have expected no queue metrics at all.

How do you check if the queue has disappeared?
I would propose to check the metrics of the exporter directly: `curl -s http://localhost:9419/metrics|less`.
Prometheus will still show the metrics for some time after they got stale.

Can you repeat the test with full config file and checking the metrics directly?
