### ISSUE TITLE
retriving system cert pool failed

### ISSUE THREAD

**Issue by EnergeticWong** [kbudde/rabbitmq_exporter#247]
Hello kris kuddle, I tried to use your exporter on windows server 2016. I wrote the config.json file. According to your example, when I run cmd, I encountered an error, which has not been solved yet. The problem is What caused it? Is it a problem with my operating system or I forgot to do something. Below is the detailed content of the file: 
config.json:
```
{
    "rabbit_url": "http://127.0.0.1:15672",
    "rabbit_user": "Teld",
    "rabbit_pass": "password",
    "publish_port": "15674",
    "publish_addr": "",
    "output_format": "TTY",
    "insecure_skip_verify": false,
    "exlude_metrics": [],
    "include_queues": ".*",
    "skip_queues": "amq.*",
    "skip_vhost": "^$",
    "include_vhost": ".*",
    "rabbit_capabilities": "no_sort,bert",
    "enabled_exporters": [
            "exchange",
            "node",
            "overview",
            "queue"
    ],
}
```

command in cmd

```
C:\TeldAPP\Monitor>rabbitmq_exporter -config-file config.json
time="2021-12-30T13:44:21+08:00" level=info msg="Using default certificate pool"
time="2021-12-30T13:44:21+08:00" level=error msg="retriving system cert pool failed" error="crypto/x509: system root pool is not available on Windows"
time="2021-12-30T13:44:21+08:00" level=info msg="Starting RabbitMQ exporter" BRANCH=HEAD BUILD_DATE="2021-12-15T21:16:24Z" REVISION=63655ff VERSION=1.0.0-RC12
time="2021-12-30T13:44:21+08:00" level=info msg="Active Configuration" CAFILE= CERTFILE= EXCLUDE_METRICS="[]" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" KEYFILE= MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=15674 RABBIT_CAPABILITIES="no_sort,bert" RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=0 RABBIT_URL="http://127.0.0.1:15672" RABBIT_USER=Teld SKIPVERIFY=false SKIP_QUEUES="amq.*" SKIP_VHOST="^$"
```

**Comment by kbudde** [comment]
Hi @EnergeticWong,

It's probably an issue with permissions.
I suspect the error will not occur, if you run the exporter "as Administrator". I will do some tests.

You can safely ignore the error as your rabbitMQ is not using https.
Is everything else working?

Best regards

Kris

**Comment by EnergeticWong** [comment]
Hi Kris,

Thank you very much for your reply. Although an error is reported, all metrics can be seen by accessing the exposed port through Chrome.


Thank you again
Wish you the best at work

Best regards

wuzw



| |
wuzw
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/30/2021 14:27，Kris ***@***.***> wrote：

Hi @EnergeticWong,

It's probably an issue with permissions.
I suspect the error will not occur, if you run the exporter "as Administrator". I will do some tests.

You can safely ignore the error as your rabbitMQ is not using https.
Is everything else working?

Best regards

Kris

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kbudde** [comment]
Won't do
