### ISSUE TITLE
Documenting the correct Grafana Dashboards to use 

### ISSUE THREAD

**Issue by sherifkayad** [kbudde/rabbitmq_exporter#248]
First of all thanks for this great project! .. I am just a bit unsure which dashboards should be the ones to use / the official Grafana Dashboards of this project? .. I came across:
- https://grafana.com/grafana/dashboards/4279
- https://grafana.com/grafana/dashboards/4371
- https://grafana.com/grafana/dashboards/2121
- https://grafana.com/grafana/dashboards/10982
- .. and of course the official RabbitMQ dashboards here https://grafana.com/orgs/rabbitmq

Could you please state which of these provide correct data / completely support the metrics exported by this project?

**Comment by kbudde** [comment]
hi @sherifkayad, 
in the past I was always using a specialized dashboard. 
Unfortunately I don't have access anymore to a rabbitmq instance with realistic data. Therefore I need help from users.
There is another ticket #114 with the same issue. If you find something usable I would be happy if you can share your results.
