### ISSUE TITLE
[Improvement] - Additional RabbitMQ metrics

### ISSUE THREAD

**Issue by atzezitman** [kbudde/rabbitmq_exporter#25]
There are several queueinfoitems that are currently not available as metric. https://www.rabbitmq.com/man/rabbitmqctl.1.man.html

- queue_durable
- queue_auto_delete
- queue_arguments
- queue_policy
- queue_exclusive
- queue_exclusive_consumer_tag
- queue_head_message_timestamp
- queue_state

Personally I was specifically looking for head_message_timestamp. Monitoring this timestamp enables me to verify there is no excessive delay in the system.
This items returns a timestamp, but for comparison in prometheus, it would be way easier if the return value was the same as time() (returns the number of seconds since January 1, 1970 UTC). Allowing for example: (time() - rabbitmq_queue_head_message_timestamp{queue="a.b",vhost="/c"}) > 120

**Comment by kbudde** [comment]
Hi,

The timestamp looks interesting. I'm going to work on it.
I will check the other metrics as well. But I think the  queue_exclusive_consumer_tag or queue_arguments are not real metrics and are tending to increase the number of timeseries or not? What is the use case for it?

"queue_durable" and "queue_autodelete" should be useful as label for filtering. 
So I would add these as well. 
Do you need more?

**Comment by atzezitman** [comment]
I actually tried to list all that are currently not availabe, and only excluded the pid attributes. I think queue_exlusive_consumer_tag and qeueu_arguments might be useful as labels, though I have no use case myself for them and think of any practical.
For me the timestamp is by far the most important one.

**Comment by kbudde** [comment]
HI,

I've created a prerelease version with all changes. 
Can you please verify that it is working.

The docker image was updated as well:
- tag:latest includes the head_message_timestamp
- tag: v0.18-dev all features of the prerelease https://github.com/kbudde/rabbitmq_exporter/releases/tag/v0.18-dev

 If there are no issues I'm going to release this version. I think I will close this issue then as well. If the other metrics are requested I'm going to add them with a new release.

Thank you for pointing me to the head_message_timestamp. Interesting (new) feature.

**Comment by nickvth** [comment]
@atzezitman v0.18-dev is running on our development environment, please test this version.

**Comment by kbudde** [comment]
merged
