### ISSUE TITLE
rabbitmq-delayed-message no data

### ISSUE THREAD

**Issue by yuyivic** [kbudde/rabbitmq_exporter#259]
I used rabbitmq-delayed-message plugin, but dashboard shows no data.
<img width="721" alt="iShot2022-04-19 14 39 38" src="https://user-images.githubusercontent.com/22007456/163946402-0f70c352-7b37-4e11-8f42-3aed8d07221c.png">
<img width="1472" alt="iShot2022-04-19 14 38 00" src="https://user-images.githubusercontent.com/22007456/163946302-54eb3829-dd32-4b12-a3f8-ad0e7d7039a2.png">

**Comment by kbudde** [comment]
Hey @yuyivic,

sorry for the late reply. I was never using this plugin. I suspect it influences the exported data of the rabbitmq.
This exporter is just fetching the data of the api.

Please have a look at the api results of the endpoint: `/api/queues`
Especially the field `message_stats.publish` is important. If this has always a value of 0 or it is not increasing over time, you will not get any metrics from it.
