### ISSUE TITLE
Issues with installing rabbitmq exporter via mesos marathon

### ISSUE THREAD

**Issue by xbblq7n** [kbudde/rabbitmq_exporter#26]
Hi,
I am facing issues with deploying rabbitmq exporter via marathon.
I have deployed rabbitmq via marathon as well.
The below command works fine when deployed directly from the server.
docker run -d --net=container:my-rabbit kbudde/rabbitmq-exporter

But in Marathon the network settings allows only bridged,host and user settings and there is no option for container network.
**--net=container:my-rabbit**
Also, since the rabbitmq is deployed via marathon the containerID and Container Name will change after every restart so this will also create problem with container network mapping.

Is there a way to run this using bridged mode.
https://docs.docker.com/engine/reference/run/#network-settings
https://docs.mesosphere.com/1.8/usage/managing-services/service-ports/

Regards
Dinesh KR

**Comment by kbudde** [comment]
Hi,
it is enough if the exporter is able to reach the rabbitmq server on port 15672 (management plugin).
So there is no need to use the shared container networking if you can link both containers the usual way.

In this case you have to export the port 9090 on the exporter container.

BR

Kris
