### ISSUE TITLE
Debian package for this exporter

### ISSUE THREAD

**Issue by kampagnol** [kbudde/rabbitmq_exporter#260]
Hi

I woud like a properly packaged binary for deployment on debian (and possibly other debian-based systemd systems); either a downloadable .DEB, or (better still) inclusion in the regular debian repositories.

It is possible to deploy using the release TAR, but the point is to have a native DEB for easy installation.

I have done some preliminary work, and managed to create a .DEB package that seems to install correctly. However, I am not an expert on the matter, and I am quite sure that it is possible to improve.

Is this something you would consider? If yes, what would be the next steps?

Regards, Kevin

**Comment by kbudde** [comment]
Hi @kampagnol ,

thank you for your interest but this is currently out of scope of this project.
