### ISSUE TITLE
rabbitmq_queue_messages_total is not sent to prometheus, while other metrics - are sent

### ISSUE THREAD

**Issue by M1ha-Shvn** [kbudde/rabbitmq_exporter#285]
Hi.
I have a strange issue when some of the metrics are absent in prometheus, and some - are not.
I have `rabbitmq_queue_messages`, `rabbitmq_queue_messages_ack_total`, `rabbitmq_queue_messages_published_total`. 
But `rabbitmq_queue_messages_total` does not return anything

I see some warnings in `/var/log/syslog`:
```
Jun 21 06:39:35 us-srv-mq-node-01 rabbitmq_exporter[554480]: time="2022-06-21T06:39:35Z" level=warning msg="error parsing idle since time" error="parsing time \"2022-06-21T06:39:16.767+00:00\" as \"2006-01-02 15:04:05\": cannot parse \"T06:39:16.767+00:00\" as \" \"" idle_since="2022-06-21T06:39:16.767+00:00"
Jun 21 06:39:35 us-srv-mq-node-01 rabbitmq_exporter[554480]: time="2022-06-21T06:39:35Z" level=warning msg="error parsing idle since time" error="parsing time \"2022-06-21T06:39:02.687+00:00\" as \"2006-01-02 15:04:05\": cannot parse \"T06:39:02.687+00:00\" as \" \"" idle_since="2022-06-21T06:39:02.687+00:00"
Jun 21 06:39:35 us-srv-mq-node-01 rabbitmq_exporter[554480]: time="2022-06-21T06:39:35Z" level=info msg="Metrics updated" duration=232.092177ms
```
Erlang version: 1:24.3.3-1
RabbitMQ version: 3.10.5-1
rabbitm_exporter version: 1.0.0-RC16

**Comment by kbudde** [comment]
Hey @M1ha-Shvn  there is no metric "rabbitmq_queue_messages_total" in this exporter.

PS: I've seen the warning about the timestamp for idle_since metric. This was fixed.

**Comment by M1ha-Shvn** [comment]
Hmm... has it ever existed? I have RabbitMQ 3.7.17 on the other cluster with rabbitmq_exporter 0.29.0 And this metric is present in prometheus results 🤔

**Comment by kbudde** [comment]
Oh, yes you are right. The metric was there in this old version.
It was replaced by `rabbitmq_queue_messages_global`.
The _total suffix is reserved for counter metrics in prometheus. Therefore it was changed.
