### ISSUE TITLE
Missing metric: consumer utilization

### ISSUE THREAD

**Issue by klinakuf** [kbudde/rabbitmq_exporter#30]
Although in the documentation it states that the metric "queue_consumer_utilisation" is available as a gauge, the exporter is not providing it.

Should I enable something or configure in Rabbit?

Thanks

**Comment by kbudde** [comment]
Hi,
it is enabled by default. But you need a) a consumer and b) a steady message flow.
Consumer Utilisation is not exported by the rabbitmq management plugin if the queues are not processing any messages. 
If the rabbitmq management plugin is not exporting the consumer utilisation, the rabbitmq exporter will not export it as well. 
If you are using grafana you should use Display styles > "Null point mode"> "null as zero" to spot missing data.

![queues](https://cloud.githubusercontent.com/assets/1072181/25176200/ab5a5bac-24fd-11e7-81b3-c914034240b4.png)

You can check the management plugin for the queues as well: If you add the "consumer utilisation" column to the queue table you will probably spot queues with utilisation "N/A".

**Comment by klinakuf** [comment]
Hi, 

Thanks for your answer, I saw that while experimenting. ;)
