### ISSUE TITLE
New metric: message size

### ISSUE THREAD

**Issue by samber** [kbudde/rabbitmq_exporter#302]
Currently, the only way to get message size is to execute the following query: `rabbitmq_queue_message_bytes / rabbitmq_queue_messages`.

It results in an average message size measured instantly. Both metrics are gauge.

It would be very nice to have a rabbitmq_queue_message_bytes_total **counter** and rabbitmq_queue_message_total **counter**, in order to have valid measurement and use `rate(...)` functions.

I wonder if a histogram could give even more information. 🤔

**Comment by kbudde** [comment]
Unfortunately this is not possible.
The exporter gets the data from the RabbitmqAPI.
Here we only have the gauge values.
