### ISSUE TITLE
RabbitMQ Exporter is losing data in stackdriver metrics

### ISSUE THREAD

**Issue by sshingarapu** [kbudde/rabbitmq_exporter#303]
Hi,

We are using rabbitmq exporter docker image(v1.0.0-RC19) in GKE to export metrics to google stack driver. We are observing that the graph for a metric "rabbitmq_queue_messages_ready" in stackdriver has gaps based on the Minimum Alignment period.

We don't see any issue with CPU and Memory consumption of RabbitMQ exporter pod and also no errors in logs. I see that this type of issue fixed in v1.0.0-RC19 as per this https://github.com/kbudde/rabbitmq_exporter/issues/131 but still we are facing the issue. 

Below is the deployment file 

`apiVersion: apps/v1
kind: Deployment
metadata:
name: rabbitmq-exporter
labels:
app: rabbitmq-exporter-metrics
spec:
replicas: 1
selector:
matchLabels:
app: rabbitmq-exporter-metrics
template:
metadata:
labels:
app: rabbitmq-exporter-metrics
spec:
containers:
- name: rabbitmq-exporter-metrics
image:
resources:
limits:
cpu: '1'
memory: 256Mi
requests:
cpu: '1'
memory: 128Mi
env:
- name: RABBIT_URL
value: https://<rabbitmq_servicename>..svc.cluster.local:15672
- name: RABBIT_CAPABILITIES
  value: no_sort
- name: RABBIT_USER
valueFrom:
secretKeyRef:
name: -default-user
key: username
- name: RABBIT_PASSWORD
valueFrom:
secretKeyRef:
name: -default-user
key: password
- name: PUBLISH_PORT
value: "9419"
- name: LOG_LEVEL
value: "debug"
ports:
- containerPort: 9419
name: publish
livenessProbe:
httpGet:
path: /
port: publish
readinessProbe:
httpGet:
path: /
port: publish
securityContext:
capabilities:
drop:
- SETPCAP
- MKNOD
- AUDIT_WRITE
- CHOWN
- NET_RAW
- DAC_OVERRIDE
- FOWNER
- FSETID
- KILL
- SETGID
- SETUID
- NET_BIND_SERVICE
- SYS_CHROOT
- SETFCAP
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 10002`

**Comment by sshingarapu** [comment]
We are observed the issue when using the filter with label "self" & its value is 0.



<img width="1482" alt="Screenshot 2022-10-31 at 12 38 31 PM" src="https://user-images.githubusercontent.com/34445086/198951559-4061a359-db25-4e37-8451-1380a27b125c.png">

**Comment by kbudde** [comment]
Hi @sshingarapu,

you'Ve spotted a known issue. If the exporter is not running as a sidecar, you have the change the `RABBIT_CONNECTION` setting to `loadbalancer`
See https://github.com/kbudde/rabbitmq_exporter/#missing-data-in-graphs

**Comment by sshingarapu** [comment]
Thanks @kbudde for your response. We have to update our helm chart to add RABBIT_CONNECTION and it may take some time due to some other reasons. Meanwhile can we remove the label "self" to fix the issue?
