### ISSUE TITLE
Not a Issue, But a request if there exists some generic Grafana Dashboard :)

### ISSUE THREAD

**Issue by thapakazi** [kbudde/rabbitmq_exporter#31]
Kudos all, just deployed an exporter hanging on a tmux session scrapping the cluster details.

**How are you guys doing the graphs**. Learning about the rabbit is still a advent, wanna start early. 
:thinking: if some us have(could share) some cool dashing boards on :rabbit: rabbit metrics.

Progress so far:
![screenshot-20170423-09 45 24](https://cloud.githubusercontent.com/assets/1695906/25310673/ab87aeea-2809-11e7-91f1-c9a4ed58e9b9.png)

Waiting for some github examples :smile:

**Comment by kbudde** [comment]
I agree. It is a good idea to add a dashboard.

I will check if I can provide a generic and usefull dashboard

**Comment by otsuarez** [comment]
Hi, 
Maybe this one https://grafana.com/dashboards/2121

**Comment by anudeepmk** [comment]
I have already running rabbit-mq (not a container), How do I utilize kbudde/rabbitmq_exporter to monitor my setup?

**Comment by DavideCarvalho** [comment]
Hello guys,
I'm trying to use this dashboard, but when I try to add the datasource and set the url to http://localhost:9090 (I tried setting to http://localhost:9090/metrics, but gives the same output) I just get ```
HTTP Error Bad Gateway```, have someone experienced this?
![chrome_2017-10-19_08-39-43](https://user-images.githubusercontent.com/15630886/31767257-1e273b7e-b4a9-11e7-8678-3c073f57dba8.png)

**Comment by kbudde** [comment]
Hi, please connect grafana to Prometheus. Prometheus will collect the data from exporters.

**Comment by kbudde** [comment]
For setting up the rabbitmq exporter you can check #51 .

I will close this ticket as there is already a dashboard.
