### ISSUE TITLE
i want to monitor more instance by one metrice

### ISSUE THREAD

**Issue by alazytomcat** [kbudde/rabbitmq_exporter#328]
this is my conf ,but it is not work

{
    "rabbit_url": "http://192.168.10.38:18500",
    "rabbit_user": "admin",
    "rabbit_pass": "admin",
    "publish_port": "18500",
    "publish_addr": "",
    "output_format": "TTY",
    "ca_file": "ca.pem",
    "LOG_LEVEL": "warning",
    "cert_file": "client-cert.pem",
    "key_file": "client-key.pem",
    "insecure_skip_verify": true,
    "exlude_metrics": [],
    "include_queues": ".*",
    "skip_queues": "^$",
    "skip_vhost": "^$",
    "include_vhost": ".*",
    "rabbit_capabilities": "no_sort,bert",
    "enabled_exporters": [
            "exchange",
            "node",
            "overview",
            "queue"
    ],
    "timeout": 30,
    "max_queues": 0
}

{
    "rabbit_url": "http://192.168.10.38:18501",
    "rabbit_user": "admin",
    "rabbit_pass": "admin",
    "publish_port": "18501",
    "publish_addr": "",
    "output_format": "TTY",
    "ca_file": "ca.pem",
    "LOG_LEVEL": "warning",
    "cert_file": "client-cert.pem",
    "key_file": "client-key.pem",
    "insecure_skip_verify": true,
    "exlude_metrics": [],
    "include_queues": ".*",
    "skip_queues": "^$",
    "skip_vhost": "^$",
    "include_vhost": ".*",
    "rabbit_capabilities": "no_sort,bert",
    "enabled_exporters": [
            "exchange",
            "node",
            "overview",
            "queue"
    ],
    "timeout": 30,
    "max_queues": 0
}

**Comment by kbudde** [comment]
Hi,

is it still an issue?

**Comment by kbudde** [comment]
Each exporter can only monitor one instance.
