### ISSUE TITLE
RabbitMQ Error while retrieving data from rabbitHost

### ISSUE THREAD

**Issue by Wilhelamm** [kbudde/rabbitmq_exporter#343]
Hi guys, I'm getting this error when I try to get the metrics of the rabbit exporter, I'm using an administrator user to log in to the exporter.

`time="2023-07-27T12:47:21Z" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="http://10.216.1.31:15672" statusCode=401`

**Comment by Dgotlieb** [comment]
same issue for me.. 
I'm using RabbitMQ version 3.11.5

**Comment by Wilhelamm** [comment]
@Dgotlieb OMG it worked like a charm, thank you for your help, I was searching for two days to fix it, thanks a lot.
Best regards!
