### ISSUE TITLE
rabbitmq_queue_messages.* not shown in prometheus

### ISSUE THREAD

**Issue by anudeepmk** [kbudde/rabbitmq_exporter#35]
i have set this up newly, I am unable to see the metrics for sum by (vhost)(rabbitmq_queue_messages_ready) and all metrics for (vhost)(rabbitmq_queue_messages.*)

Do I need to enable any thing else? or set up any env variables?
I am using latest rabbitmq_exporter-0.20.0.linux-amd64.tar.gz and my rabbitmq is not a docker container
<img width="1060" alt="screen shot 2017-06-19 at 9 16 59 pm" src="https://user-images.githubusercontent.com/20853848/27297138-bafc9e82-5534-11e7-960c-f09f41050187.png">

**Comment by anudeepmk** [comment]
did anyone face this issue or are there any parameters/Env variables to be set before running rabbitmq_exporter?

**Comment by kbudde** [comment]
Hi @anudeepmk,

on a normal rabbitmq installation with [management_plugin enabled](https://www.rabbitmq.com/management.html) it is possible to retrieve the data with guest credentials from localhost. In this case the rabbitmq_exporter does not need any configuration if it is running on the same host. 

Did you check the log of the rabbitmq_exporter? It is logging an info message for every successfull fetch or an error otherwise.
You could check as well the output of the exporter under http://localhost:9090/metrics

BR

Kris

**Comment by anudeepmk** [comment]
Hi @kbudde 
I checked the log of rabbitmq_exporter(nohup.out in my case)

{"level":"info","msg":"Metrics updated successfully.","time":"2017-06-20T19:33:22Z"}
{"level":"info","msg":"Metrics updated successfully.","time":"2017-06-20T19:33:37Z"}
{"level":"info","msg":"Metrics updated successfully.","time":"2017-06-20T19:33:52Z"}

It does log the metrics, Also I checked http://localhost:9099/metrics, I do not see any metrics for "rabbitmq_queue_messages.*"

I see the below from /metrics

rabbitmq_node_mem_used{node="rabbit@<ipaddr>",vhost=""} 3.67280264e+08
# HELP rabbitmq_queuesTotal Total number of queues in use.
# TYPE rabbitmq_queuesTotal gauge
rabbitmq_queuesTotal 19

I am not using the guest user for rabbitmq_exporter,
So to get those metrics do I need to enable management_plugin?
please advise

Thanks,
anudeep

**Comment by anudeepmk** [comment]
Hi Kris,

I checked it and also my rabbitmq exporter and rabbitmq server are on the same host, so should i not mention the ENV parameters like "INCLUD_QUEUES" and "SKIP_QUEUES" etc?

Thanks,
anudeep

**Comment by anudeepmk** [comment]
That does work for me now Kris!

Thank you!

**Comment by leoncard** [comment]
Hi there,

My exporter is also lacking some queue metrics. I have `rabbitmq` version `3.6.3` installed, I just wonder if that could be the reason why the exporter is not exposing some metrics.

Like the `OP` my `rabbitmq` is not `dockerized`. 
My exporter runs on a `kubernetes` environment on a different machine. 
I am using the latest exporter and I also got `rabbitmq_management` installed. 

The queue metrics currently being exposed are:

```
rabbitmq_queue_messages_ready_total
rabbitmq_queue_messages_total
rabbitmq_queue_messages_unacknowledged_total
rabbitmq_queuesTotal
```

KR,

Leo
