### ISSUE TITLE
Build Instructions for binary

### ISSUE THREAD

**Issue by thinkpoddr** [kbudde/rabbitmq_exporter#361]
Build instructions for binary is missing.

This also plays into the Dockerfile, where obviously the part of the build process is cut out. Instead, just the precompiled binary of some origin is copied into it, which is also not part of the repository.

I'd like to have the full build Dockerfile in order to be able to reproduce your binary.

It is even not that obvious if the provided source even produces the binaries provided.

**Comment by kbudde** [comment]
Hey, you are right the project is lacking build instructions.

Building is quite simple: Builds are done using [goreleaser](https://goreleaser.com/),
e.g. `goreleaser build --snapshot`

What is goreleaser doing:

1. Build the binaries for all configured systems and architectures
2. Build the container and copy the binary in the container

Hope this helps
