### ISSUE TITLE
Add RabbitMQ Stream metrics

### ISSUE THREAD

**Issue by francescopessina87** [kbudde/rabbitmq_exporter#375]
When the `rabbitmq_stream` and `rabbitmq_stream_management` plugins are enabled, some useful metrics on the streams connections, publishers and consumers are exposed via the following apis:

- `api/stream/connections/**`
- `api/stream/publishers/*`
- `api/stream/consumers/*`

It would be very useful that these metrics would be exported by this exporter :)

**Comment by kbudde** [comment]
@francescopessina87 I decided to stop accepting new features. See #383
