### ISSUE TITLE
Show users making connections

### ISSUE THREAD

**Issue by munai-das** [kbudde/rabbitmq_exporter#38]
/api/connections gives user details. Can we have user based labels to connections?

{u'auth_mechanism': u'PLAIN',
 u'channel_max': 65535,
 u'channels': 1,
 u'client_properties': {u'copyright': u'Copyright (c) 2007-2014 VMWare Inc, Tony Garnock-Jones, and Alan Antonuk.',
  u'information': u'See https://github.com/alanxz/rabbitmq-c',
  u'platform': u'linux-gnu',
  u'product': u'rabbitmq-c',
  u'version': u'0.5.3-pre'},
 u'connected_at': 1501868641834,
 u'frame_max': 131072,
 u'garbage_collection': {u'fullsweep_after': 65535,
  u'min_bin_vheap_size': 46422,
  u'min_heap_size': 233,
  u'minor_gcs': 3},
 u'host': u'172.31.15.10',
 u'name': u'172.31.0.130:32769 -> 172.31.15.10:5672',
 u'node': u'rabbit@rmq-cluster-node-04',
 u'peer_cert_issuer': None,
 u'peer_cert_subject': None,
 u'peer_cert_validity': None,
 u'peer_host': u'172.31.0.130',
 u'peer_port': 32769,
 u'port': 5672,
 u'protocol': u'AMQP 0-9-1',
 u'recv_cnt': 22708,
 u'recv_oct': 8905713,
 u'recv_oct_details': {u'rate': 169.6},
 u'reductions': 6257210,
 u'reductions_details': {u'rate': 148.8},
 u'send_cnt': 6,
 u'send_oct': 573,
 u'send_oct_details': {u'rate': 0.0},
 u'send_pend': 0,
 u'ssl': False,
 u'ssl_cipher': None,
 u'ssl_hash': None,
 u'ssl_key_exchange': None,
 u'ssl_protocol': None,
 u'state': u'running',
 u'timeout': 0,
 u'type': u'network',
 u'user': u'rmq_oms',
 u'vhost': u'/'}

Also will like to add host, name , node to it.

**Comment by kbudde** [comment]
Hi,

I'm going to add metrics from the connection endpoint. But I think they should be disabled by default.
If connections are not long-living this metric would create a high number of orphaned metrics.
