### ISSUE TITLE
API endpoints not working

### ISSUE THREAD

**Issue by imorpher** [kbudde/rabbitmq_exporter#39]
I am in the process of setting up a grafana dashboard to monitor our rabbitmq queues and came across this exporter.

I have been able to setup the rabbitmq_exporter itself and can successfully see metrics on /metrics but I am having issues with connecting my grafana instance to it. 

I am just trying to set it up like a normal prometheus data source in grafana but it looks like the /api endpoints are not working for me. 

Any requests to an api end point such as 
`http://localhost:9090/api/v1/query_range?query=prometheus_evaluator_duration_seconds%7Bquantile!%3D%220.01%22%2C%20quantile!%3D%220.05%22%7D&start=1502797539&end=1502797839&step=2`

redirects me to the landing page

![image](https://user-images.githubusercontent.com/1525494/29314984-9608e0a8-81b8-11e7-8062-258a174db706.png)
Is this a known issue or have I misinterpreted this project?

**Comment by kbudde** [comment]
HI @imorpher,

you are missing one important part of the puzzle:

The RabbitMQ Exporter provides metrics to be scrapted by **prometheus**. Prometheus will serve the data for grafana.

Prometheus installation is quite easy. To get started you just need to create a config file and start the binary: https://prometheus.io/docs/introduction/getting_started/

You should check as well the long list of exporters. Perhaps you have more application you can already monitor: https://prometheus.io/docs/instrumenting/exporters/

If you have further question. You can try to reach me on gitter. https://gitter.im/rabbitmq_exporter/Lobby


BR

Kris
