### ISSUE TITLE
Metrics for partitions

### ISSUE THREAD

**Issue by peimanja** [kbudde/rabbitmq_exporter#40]
Is it possible to add metrics for [partitions](https://www.rabbitmq.com/partitions.html)? It is very useful to detect if the cluster is healthy or a split brains happened.
it is available on `http://localhost:15672/api/nodes`
```
{partitions,[{rabbit@smacmullen,[hare@smacmullen]},
 =>               {hare@smacmullen,[rabbit@smacmullen]}]}]```
A healthy cluster has no partitions 
```
```
{"partitions":[] ...
```
So I guess it can be a `global` metric with the value of `0` or more.

**Comment by kbudde** [comment]
Hi,

it sounds useful. I'll add it as soon as I have some time.

BR

Kris

**Comment by peimanja** [comment]
Cheers
