### ISSUE TITLE
grafana error: a.data.data is undefined

### ISSUE THREAD

**Issue by mahapundit** [kbudde/rabbitmq_exporter#44]
After executing 
  $ docker run -d -e RABBITMQ_NODENAME=my-rabbit --name my-rabbit -p 15672:15672 -p 9090:9090 rabbitmq:3-management

and 

 $ docker run -d --net=container:my-rabbit kbudde/rabbitmq-exporter

metrics is availible at http://localhost:9090/metrics
but when importing the dashboard in grafana, It shows error that a.data.data is undefined .

![screenshot from 2017-09-08 00-36-21](https://user-images.githubusercontent.com/19945629/30204839-86bf7342-94a4-11e7-88c7-e1078408c034.png)

Please help.

**Comment by kbudde** [comment]
Hi,
Is your Prometheus scraping the exporter data?

See comment on #39.

I think I have to add some documentation. 
BR

**Comment by kbudde** [comment]
Grafana has to connect to prometheus. Prometheus can scrape the exporter.

Closing this issue
