### ISSUE TITLE
How to monitor the particular Queue through Rabbitmq Exporter

### ISSUE THREAD

**Issue by MobinAnsari** [kbudde/rabbitmq_exporter#51]
Hi Team, 

I have installed Rabbitmq Exporter as given on the github website but all the metrics are showing as Value 0 even after the RabbitMQ is already installed on the server. Also I want to monitor the no. of messages in particular queue(postupload.queue).  How can I achieve this through the given rabbitmq exporter and prometheus.

Awaiting for your immediate response.

Regards,
Mobin Ansari

**Comment by kbudde** [comment]
Hi,

if I understand you correct. You have [installed prometheus](https://prometheus.io/docs/introduction/install/) and configured one job for the rabbitmq exporter ([Getting started](https://prometheus.io/docs/introduction/getting_started/)).

RabbitMQ server is up and running. [Management plugin](https://www.rabbitmq.com/management.html) is installed.

### Testing rabbitmq exporter
If you open the website or curl: http://rabbitmqExporterHost:9090/metrics you should see all the metrics as text. 
If you don't see any rabbitmq_queue metrics you have probably issues in the connection between exporter and rabbitmq.
You should check the log of the exporter. It will log error messages.
If the data is there you should check prometheus.

### Prometheus
If the exporter is showing data, prometheus has to retrieve the data. First you should check the status of the targets if the exporter is up and scraped.

In prometheus you should check the metrics. Depending on your usage it can be normal that there are no messages waiting.

The query 
`rabbitmq_queuesTotal`
should return the number of queues in your rabbitmq server.

The query
`rabbitmq_queue_messages_delivered_total`
should return one metric for each queue showing the total number of all delivered messages. If you have many queues you can filter the list:
- `rabbitmq_queue_messages_delivered_total>0`
- `rabbitmq_queue_messages_delivered_total{queue=~".*postupload.*"}`

If you are already using rabbitmq you should find some queues with delivered messages.

--
Can you describe a bit more what is not working and what is working? I will try to help you.

Best regards

Kris

**Comment by MobinAnsari** [comment]
Hi kbudde,

I have attached screenshot of rabbitmq management, Prometheus and Rabbit MQ Exporter Metrics. 
You can see that metrics are there in exporter but when I query the rabbitmq_queuesTotal in proemtheus, I am getting value as 0. We have more than 15 queues already created in rabbitmq.  I am not getting data in any of the rabbitmq metrics. Further, please let me know where I can find the log of the exporter.
![exporter-metrics](https://user-images.githubusercontent.com/28623010/31937701-f42d1ce8-b8d2-11e7-9835-7ac92b6990be.JPG)
![rabbitmq-manage](https://user-images.githubusercontent.com/28623010/31937595-9db9f818-b8d2-11e7-86e1-033298814e18.JPG)
![prom](https://user-images.githubusercontent.com/28623010/31937695-ed082e1c-b8d2-11e7-8be0-9eaae5022b5d.JPG)

Please provide the solution of the same.

Your help would be highly appreciable.

Awaiting for your response.

Regards,
Mobin Ansari

**Comment by kbudde** [comment]
Hi @MobinAnsari ,

I'm sorry for the late reply  I've not seen your response.
The screenshot of the exporter is showing the same data as prometheus. It looks "correct".
Were you able to solve your issue?

Maybe the user for scraping is missing some permissions on vhosts/queues/exchanges?

BR,
Kris

**Comment by valentin-krasontovitsch** [comment]
Hi @kbudde - I unfortunately wasn't able to find any documentation on which permissions a user has to have on a given virtual host to extract information, e.g. consumers on queues on said vhost.

I have a user without any permissions, with `monitoring` tag, and with that use I get out general info (like total number of consumers, but not as mentioned above info about the # of consumers on a specific queue.

After giving full read permissions on the relevant vhost, I seem to be getting the info I needed - perhaps this could be documented somewhere? How to setup a user with monitoring tag, and the necessary permissions, for use by the exporter, in case that the two containers don't share a network / there is no guest user / other reasons?
