### ISSUE TITLE
Change default port to some unique value

### ISSUE THREAD

**Issue by pkoziol** [kbudde/rabbitmq_exporter#53]
9090 is already used by Prometheus. According to [the documentation](https://prometheus.io/docs/instrumenting/writing_exporters/#port-numbers) exporters should use register unique port number on the wiki and use it.

**Comment by kbudde** [comment]
@pkoziol you are right. Using the same port as Prometheus was not a good decision.
I was thinking about a 1.0 release. It's perfect to be included.

**Comment by kbudde** [comment]
Added reservation: 9419 
https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Comment by uttamanand** [comment]
Hi,

So rabbitmq_exporter just needs to be installed on the VM giving the rabbitmq_hostname:15672 ?
Don't we need to put the plugin ( *.ez file) in the plugin folder and enable it using enabled_plugin file?

Thanks
Uttam
