### ISSUE TITLE
Metrics Partition - Returns 0 In A Partitioned Network

### ISSUE THREAD

**Issue by gdmello** [kbudde/rabbitmq_exporter#54]
**RabbitMq Version:** `RabbitMQ 3.6.10, Erlang 19.2.1`
**Version:** `v0.23.0`
# Issue
My RabbitMq cluster is currently partitioned, each of the 4 nodes is in a partition. RabbitMQ management UI, rabbitmqctl and the HTTP API all indicate a partitioned cluster, but the rabbitmq_exporter returns `rabbitmq_partitions` as 0.

## RabbitMQ management UI
![image](https://user-images.githubusercontent.com/1682431/33134660-4e03a398-cf6e-11e7-8429-ae307283ec66.png)

## Rabbitmqctl:
```
root@ribbit-0:/# rabbitmqctl cluster_status
Cluster status of node 'rabbit@ribbit-0'
[{nodes,[{disc,['rabbit@ribbit-0','rabbit@ribbit-1','rabbit@ribbit-2',
                'rabbit@ribbit-3','rabbit@ribbit-4']}]},
 {running_nodes,['rabbit@ribbit-0']},
 {cluster_name,<<"rabbit@ribbit-1.ribbit.pie2.svc.cluster.local">>},
 {partitions,[{'rabbit@ribbit-0',['rabbit@ribbit-1','rabbit@ribbit-2',
                                  'rabbit@ribbit-3','rabbit@ribbit-4']}]},
 {alarms,[{'rabbit@ribbit-0',[]}]}]
```

## HTTP API
```
$ root@tdr:/home/user# curl -i http://rmq.k8s.cluster-points.com/api/nodes/rabbit@ribbit-2
{"partitions":["rabbit@ribbit-0","rabbit@ribbit-1","rabbit@ribbit-3","rabbit@ribbit-4"],"os_pid":"411","fd_total":1048576,
...
```

## Prometheus console
![image](https://user-images.githubusercontent.com/1682431/33135027-4c90ed62-cf6f-11e7-9870-071cdcbb351d.png)

It appears that the exporter is [looking](https://github.com/kbudde/rabbitmq_exporter/blob/master/exporter_overview.go) up the `/api/overview` API to determine partition count, but this api does not [expose](https://pulse.mozilla.org/doc/stats.html) partition info. Rather, partition info is available on the `/api/nodes` endpoint.

**Comment by kbudde** [comment]
Hi,

this was a really bad mistake. I hope it was not causing any issues.
I've created a new release fixing the problem.

Thank you for your very helpfull details.

Best regards

Kris Budde

**Comment by gdmello** [comment]
Thanks @kbudde! It was on a test cluster so no harm done :)
