### ISSUE TITLE
How to monitor queue depth?

### ISSUE THREAD

**Issue by helderco** [kbudde/rabbitmq_exporter#65]
Hi, I've setup the exporter using docker, and testing prometheus in my machine. Everything seems to be hooked up correctly. `/metrics` endpoint is fine, logs have no errors, prometheus is getting all sorts of metrics as expected.

For example, I have 3 celery queues. Looking at the `rabbitmq_queue_messages_delivered_total{durable="true"}`graph, the lines are increasing as expected. 

The problem is `rabbitmq_queue_messages{durable="true"}` is a flat line at 0 for all queues.

I would expect to see it going up and down as the queue is getting new tasks and processing them out to celery. Am I assuming wrong?

**Comment by helderco** [comment]
Here are some screenshots.

![screen shot 2018-01-23 at 15 04 53](https://user-images.githubusercontent.com/174525/35286212-e4c2b4fc-004e-11e8-92bc-22965f98c472.png)

![screen shot 2018-01-23 at 15 05 23](https://user-images.githubusercontent.com/174525/35286222-eb2a814e-004e-11e8-9218-09b97d8933a8.png)

**Comment by helderco** [comment]
`rabbitmq_queue_messages_ready` and `rabbitmq_queue_messages_unacknowledged_total` are also flat lines at zero.

**Comment by helderco** [comment]
I only get something on (from `queue_messages_*`):
- `rabbitmq_queue_messages_ack_total`
- `rabbitmq_queue_messages_delivered_total`
- `rabbitmq_queue_messages_published_total`

**Comment by kbudde** [comment]
Can you stop or throttle down your consumers?
Then you will see the other metrics increasing as well. 
I suspect your consumers are fast enough to handle incoming messages directly.

**Comment by helderco** [comment]
I see... the extractor would have to gather metrics at the exact milliseconds, to record these messages. I do think they are consumed very quickly. That would explain it. I'll have to make some tests tomorrow, thanks!

**Comment by helderco** [comment]
I stopped the worker and left the beat on. The queue increased as new tasks were arriving but not being consumed. Thanks, again.
