### ISSUE TITLE
Can we convert this into a Cloud-Foundry app ?

### ISSUE THREAD

**Issue by SamwiseGambgee** [kbudde/rabbitmq_exporter#69]
Hello!
I need to tunnel to the rabbitmq host to get to the port: `15672`. Is there any way where I can tunnel? Or converting this app to a CF app

**Comment by kbudde** [comment]
Hi,

the exporter needs http(s) access to the rabbitmq management interface.
I'm not aware how cloud foundry apps are working but I would expect that you can configure the access rules/tunnel from one app to another in your infrastructure.
If direct access is not possible you can try to use a proxy in front of the rabbitmq management plugin.

**Comment by SamwiseGambgee** [comment]
Hello @kbudde, thanks for the reply!
i did figure a way out for this. i have a patch which fixes the issues.
But I do see an error:
`2018-03-07T19:18:03.75+0530 [APP/PROC/WEB/0] ERR time="2018-03-07T13:48:03Z" level=error msg="Error while retrieving data from rabbitHost" error="Get https://XX.XX.XX.XX:XXXXX/api/exchanges: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" host="https://XX.XX.XX.XX:XXXXX" statusCode=0`
Any clue what is going on here?
How to manage timeouts?

**Comment by Admin-Itecbrazil** [comment]
i did have same isse @SamwiseGambgee:

time="2018-03-09T17:48:21Z" level=error msg="Error while retrieving data from rabbitHost" error="Get http://10.50.1.6:15672/api/nodes: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" host="X:15672" statusCode=0

I configure in global environment docker "SKIPVERIFY=true" but don't working too.

What can this be?

**Comment by SamwiseGambgee** [comment]
Hey @Admin-Itecbrazil , I solved my issue by setting the RABBIT_URL to 'http' instead of 'https'.
I did this setting in the manifest.yml- yes, hardcoded the RABBIT_URL, which i feel is not a good approach.

**Comment by SamwiseGambgee** [comment]
@kbudde I think we can close this thread.

**Comment by Admin-Itecbrazil** [comment]
I keep gettting the same error after changing RABBIT_URL  to 'http'.
I going open another issue for to resolve this problem.
