### ISSUE TITLE
RABBIT_URL behavior

### ISSUE THREAD

**Issue by lunaqdm** [kbudde/rabbitmq_exporter#75]
The logic around the 'RABBIT_URL' flag assumes that all URLs will start with a prefix matching `https?://`. When I did not include this prefix (i.e., was doing internal routing and did not bother to set the protocol), the exporter silently set the URL to be the default `http://localhost:15672`. There are plenty of use cases like mine, where the protocol prefix is unnecessary; whether or not you want to keep this behavior, it would be nice to have some kind of error message generated and also some documentation.

Thanks!

**Comment by kbudde** [comment]
Hi,

I've added an error during startup and a note in the readme for the moment.

What url are you using for your usecase?
//rabbitserver:15672

I'll see if I can add it.

**Comment by lunaqdm** [comment]
The URL I'm using is of the form `rabbitmq.<company-specific-stuff>.io`, which is typical of how we set up internal routing. I was able to make it work by throwing an 'http://' on the front -- so it is nice to have the note in the readme, thanks.
