### ISSUE TITLE
Scrape interval and timeout logic?

### ISSUE THREAD

**Issue by lunaqdm** [kbudde/rabbitmq_exporter#77]
Hi!

Would it be possible to add a flag to manually set the scrape timeout? I am not sure I understand how the timeout is set right now -- on the one hand, from glancing at the code, it looks like the default timeout is 15s. However, from some of your responses to various questions, it does seem that the timeout depends on how often Prometheus scrapes the endpoint.

Why I ask: Prometheus keeps (once every hour or two at least) claiming that the RabbitMQ Exporter is down, and when I look at the RabbitMQ Exporter logs I see:

```
time="2018-04-12T23:09:37Z" level=error msg="Error while retrieving data from rabbitHost" error="Get http://rabbitmq.<company-specific>.io:80/api/exchanges?sort=: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" host="http://rabbitmq.<company-specific>.io:80" statusCode=0
```

When this error occurred, I had my Prometheus scrape interval at 30s and timeout at 15s. I just increased both to 60s, so that may help significantly -- we'll see.

Thanks so much for your responsiveness to all my questions, and for building such a useful tool!

**Comment by kbudde** [comment]
Hi,

Prometheus is providing the scrape intervall to the exporter. I'm going to honor this header. 
Unfortunately it looks like I need to rewrite the exporting part to be able to handle this. It will take some more time.

**Comment by lunaqdm** [comment]
For the scrape interval, this behavior seems very reasonable - convenient to be able to set this in Prometheus and have the interval propagate automatically to the exporter. Thanks!

What is the current behavior for the scrape timeout? Is it the same as the Prometheus scrape timeout? Or is it the same as the scrape interval? Or is it some other default or something? I understand that adding a flag would be significant extra work, so until you do have the time to add this it would be really useful to have some documentation around the scrape timeout's behavior.

Thanks!

**Comment by kbudde** [comment]
I've added a parameter for setting the client timeout for now. New default value is 30s

**Comment by lunaqdm** [comment]
Looks great, thank you!
