### ISSUE TITLE
Exporter Does not run

### ISSUE THREAD

**Issue by nexusguy59** [kbudde/rabbitmq_exporter#78]
Hey Guys,

I am trying to get this running we now have a need for it. I am using it this way:

Start RabbittMQ: 
docker run -d -e RABBITMQ_NODENAME=rey-rabmq-001 --name rey-rabmq-001 -p 9419:9419 --label triton.cns.services="snmpexp" --label triton.network.public="Dev Web" rabbitmq:3-management
**The above works fine**

Start Exporter:
docker run -d --net=container:rey-rabmq-001 -e RABBIT_CAPABILITIES=bert,no_sort -e PUBLISH_PORT=9419 kbudde/rabbitmq-exporter

**_The above gives me this error:_**
**docker: Error response from daemon: (NotImplemented) Container networking is not supported is not implemented (5ab105bc-822c-4745-b91c-05423dcf3392).**

The above is happening because in the cloud it will not let you attach to an ip address. Is there a way to give the exporter it's own address and scrap the server at another address on the same network?

Not sure how to fix this any help would be appreciated, 

I am assuming the -e RABBIT_URL=http://ip.here:15627 -e RABBIT_USER=user -e RABBIT_PASSWORD=userpwd 
Lets us connect to the rabbitmq server and the user and password allows us access to scrap but which port do we scrap from?

I figured this out .... you can close this.

Thanks,

**Comment by kbudde** [comment]
Hi,

you can run rabbitmq on its own:

    docker run -d -e RABBITMQ_NODENAME=rey-rabmq-001 --name rey-rabmq-001 --label triton.cns.services="snmpexp" --label triton.network.public="Dev Web" rabbitmq:3-management

create user with monitoring right

    docker exec -ti rey-rabmq-001 rabbitmqctl add_user user userpwd
    docker exec -ti rey-rabmq-001 rabbitmqctl set_user_tags user monitoring

run rabbitmq exporter and link it to rabbitmq

    docker run -d --link rey-rabmq-001 -e RABBIT_URL=http://rey-rabmq-001:15672 -e RABBIT_USER=user -e RABBIT_PASSWORD=userpwd -e RABBIT_CAPABILITIES=bert,no_sort -e PUBLISH_PORT=9419 -p 9419:9419 kbudde/rabbitmq-exporter

you can access the metrics on port 9419 on the rabbitmq exporter.


ps: port of the management plugin is 15672
