### ISSUE TITLE
Exchanges metrics are not scrapped

### ISSUE THREAD

**Issue by chefchef** [kbudde/rabbitmq_exporter#80]
Hi, my name is Eduard. I doing a grafana dashboard with all the metrics that this rabbitmq_exporter can do. All is ok with overview and queues. But when I try to add the exchange metrics only I obtain this metrics:
rabbitmq_exchange_messages_published_in_total
rabbitmq_exchange_messages_published_out_total

The others metrics are not listed in exporter. Is it a bug in the scrapping?

Thanks!
P.D. I tried this in my local machine and I have the same behaviour.

> 1) docker run -d -e RABBITMQ_NODENAME=my-rabbit --name my-rabbit -p 9419:9419 -p 8080:15672 rabbitmq:3-management
> 2) docker run -d --net=container:my-rabbit -e RABBIT_CAPABILITIES=bert,no_sort -e PUBLISH_PORT=9419 kbudde/rabbitmq-exporter
> 3) Create and exchange, binding and queues. Publish some messages
> 4) Go to metrics http://localhost:9419/metrics

**Comment by kbudde** [comment]
Hi, 
there are just these two metrics for exchanges. 
I've misinterpreted the rabbitmq documentation.
I will remove the spare metrics from the documentation.

**Comment by chefchef** [comment]
Thanks!
