### ISSUE TITLE
Run with env CAFILE

### ISSUE THREAD

**Issue by beylisstan** [kbudde/rabbitmq_exporter#82]
Hi,

If I am running exporter with environment CAFILE, I can't see that this configuration is applying:

![rabbit_ca](https://user-images.githubusercontent.com/37801987/39671945-26d63a36-512a-11e8-9ab0-be31224c2e98.png)

And exporter can't collect metrics with following errors:
![rabbit_mq_error](https://user-images.githubusercontent.com/37801987/39671918-e5769cf2-5129-11e8-9cec-ac7031a8c6bd.png)

**Comment by kbudde** [comment]
Hi,

you need to change the RABBIT_URL to "http**s**://..."
I think it will work then.

BR

Kris
