### ISSUE TITLE
rabbitmq_exporter - getting error 'statusCode=406'

### ISSUE THREAD

**Issue by srini3463** [kbudde/rabbitmq_exporter#83]
Hi,

   When I am trying to run rabbitmq_exporter using command 'PUBLISH_PORT=9419 RABBIT_CAPABILITIES=bert,no_sort RABBIT_URL=http://rmqdev:15672 RABBIT_USER=user1 RABBIT_PASSWORD='user1' ./rabbitmq_exporter' getting below error.

ERRO[0014] Error while retrieving data from rabbitHost   error="<nil>" host="http://rmqdev:15672" statusCode=406

After changing http to https in same command, Getting below error:

ERRO[0004] Error while retrieving data from rabbitHost   error="Get https://rmqdev:15672/api/exchanges?sort=: http: server gave HTTP response to HTTPS client" host="https://rmqdev:15672" statusCode=0

Is it mandatory to to update environment variables ? Because I am passing parameter values in command itself.

Please let me know if I am missing something in setup.

Thanks.

**Comment by srini3463** [comment]
@kbudde Can you please look into the above issue.

Thanks.

**Comment by kbudde** [comment]
Hi,

Follow up from gitter:
Rabbitmq 3.5 does not support no_sort or bert

BR
