### ISSUE TITLE
Overview values ignores exclusions

### ISSUE THREAD

**Issue by maksimru** [kbudde/rabbitmq_exporter#87]
I have noticed metrics like queue_messages_ready_total ignores specified SKIP_QUEUES and INCLUDE_QUEUES settings, it will be cool if we can make aggregation based on our own filtered metrics, otherwise it can provide wrong data

**Comment by kbudde** [comment]
Hi,

the queue_messages_ready etc. are metrics of the whole cluster. They are provided by rabbitmq api.

If you need the values based on the filters, you have to calculate them using promql:
e.g.
- sum (rabbitmq_queue_messages_ready)
- sum by (vhost)(rabbitmq_queue_messages_ready)

If you need this metrics very often, you should have a look at https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/
