### ISSUE TITLE
File handle leak

### ISSUE THREAD

**Issue by bitplane** [kbudde/rabbitmq_exporter#9]
I left this running for a few days on an AWS box with the wrong Rabbit password and it eventually ran out of file handles, depleting 7-8 per minute until it consumed all 1024. (See [ls.txt](https://github.com/kbudde/rabbitmq_exporter/files/401530/ls.txt))

See [log.txt](https://github.com/kbudde/rabbitmq_exporter/files/401533/log.txt) for stderr output.

**Comment by kbudde** [comment]
Hi,

I'm pretty sure that you are using an old version.
I've tested it. v0.12.0 is the last affected version of this issue.

Can you try to upgrade the used version.

**Comment by kbudde** [comment]
@bitplane can you please verify if everything is working with the latest version.

**Comment by bitplane** [comment]
Yes this was fixed in the latest version. Apologies for the delay in testing it.
