### ISSUE TITLE
Add Queue and Connection status metrics

### ISSUE THREAD

**Issue by muralikanagala** [kbudde/rabbitmq_exporter#91]
Queue and Connection status metrics would be really helpful while troubleshooting rabbitmq issues.
I have tried adding that feature but was not successful because I am new to golang. 
Is that something already taken care or on the road map?

**Comment by kfreem02** [comment]
Rabbit UI shows State column (Idle, Running, Blocked, Blocking, Flow, etc) for queues, connections and channels .  Would be nice to have those values as a label either within an existing metric or as a separate metric.

**Comment by muzili1** [comment]
Queues
Labels: vhost, queue, durable, policy     
about queue_messages_ready，queue_messages_unacknowledged ...... is not unknown.  why?

**Comment by kbudde** [comment]
I've added two new metrics in v1.0 branch.
https://github.com/kbudde/rabbitmq_exporter/tree/v1.0

Can you please check if the metrics queue_status and connection_status are usefull for you?

**Comment by gaizeror** [comment]
@kbudde can you create a binary / how to create a binary? it's not on the release folder

**Comment by kbudde** [comment]
Hi,

I've created now a pre-release:
https://github.com/kbudde/rabbitmq_exporter/releases/tag/v1.0-wip1

Inside are two new metrics: queue_status and connection_status.
Labels:
queue_status: vhost, queue, state
connection_status: vhost, node, peer_host, user, state

Both metrics are constant 1. The state is representing the queue/connection state (running, blocked, etc.).
So you can monitor for queue_status{state="blocked"}>0 or delta(queue_status{state="running"}[1m])<0

**Comment by gaizeror** [comment]
@kbudde 
Hi, looks like the queue state is always on "running" mode even if the queue is "idle"
will make sure when one of my queues will get stuck

**Comment by kbudde** [comment]
@gaizeror did the status change in the meantime?
Can you send me the data of the /api/queues endpoint. I want to check the response of the rabbitmq.

**Comment by RicoToothless** [comment]
ask a small question. (I am new here)
About troubleshooting, is there have any way to set up multi `RABBIT_URL`?

**Comment by kbudde** [comment]
@RicoToothless It is not possible. You can setup one exporter per rabbitmq #92 
If you have more questions please file a new issue.
