### ISSUE TITLE
Add label self="1" to identify metrics that belong to the cluster node performing the scrape

### ISSUE THREAD

**Issue by kfreem02** [kbudde/rabbitmq_exporter#92]
Suggest adding label self="1" to identify metrics that belong to the node performing the current scrape.

Reason: Greatly simplify identification of authoritative metrics.

Example: 3-node cluster, each cluster-wide metric is returned  3*3=9 times.  Only 3 of them are from a "self" node, the other 6 are "last-reported" values, and are not reliable under high load.

We currently introduce a synthetic label (nodenum) in the query to perform a join on the authoritative node name.  Each node has a unique numeric suffix:
<code>label_replace(irate(rabbitmq_connection_send_bytes{environment="$environment",nodetype="$nodetype"}[2m]), "nodenum", "$1", "instance", ".*?(\\d+)")
    AND
label_replace(irate(rabbitmq_connection_send_bytes{environment="$environment",nodetype="$nodetype"}[2m]), "nodenum", "$1", "node", ".*?(\\d+)")<code>

With a "self" label, the above query could be replaced by:
`irate(rabbitmq_connection_send_bytes{self="1",environment="$environment",nodetype="$nodetype"}[2m])`

**Comment by steven-sheehy** [comment]
Other possibility is to add an ability to exclude node label so it doesn't multiply the metrics unnecessarily for people that don't need that info. A lot of people run the rabbitmq as a sidecar on each rabbitmq node instead of standalone, making the node label unnecessary.

**Comment by gdmello** [comment]
@steven-sheehy - thank you for pointing me to this issue!

I've run into this issue as well, and to circumvent the multiplication of metrics [suggested](https://github.com/helm/charts/issues/8236) we do not use the exporter as a sidecar, but rather as a single exporter for the entire cluster.
