### ISSUE TITLE
Queues  Labels: vhost, queue, durable, policy   is not scrapped

### ISSUE THREAD

**Issue by muzili1** [kbudde/rabbitmq_exporter#94]
I use rabbitmq_exporter-0.28.0.linux-amd64.tar.gz .but the metrics is not have   
Queues  Labels: vhost, queue, durable, policy:
       queue_messages_ready
       queue_messages_unacknowledged

I don't  know why?

**Comment by ramato-procon** [comment]
I can confirm this. Queue labels are missing

**Comment by muzili1** [comment]
@ramato-procon     I get it, Thanks, I really appreciate your help.
