### ISSUE TITLE
How to monitor the CPU utilization rate of RabbitMQ

### ISSUE THREAD

**Issue by tangxuye** [kbudde/rabbitmq_exporter#99]
I have used rabbitmq exporter for two weeks in my work. However, I did not find the metrics about CPU Usage rate of it.I want to monitor the CPU usage of rabbitmq.Is there any kind of CPU metrics in rabbitmq exporter?If it hasn't it, do you have any good suggestion?

**Comment by kbudde** [comment]
Hi,

monitoring cpu usage is not supported or planned to be inside this exporter.
Personally I'm using node_exporter for monitoring the cpu usage on the host:
https://www.robustperception.io/understanding-machine-cpu-usage
I'm planning to create a grafana dashboard combining metrics of rabbitmq_exporter and node_exporter. Perhaps this could help.

There is as well another rabbitmq exporter which integrates in rabbitmq as plugin. I've seen that they have more internal metrics of the erlang vm. Depending on your requirements it could be worth a try:
https://github.com/deadtrickster/prometheus_rabbitmq_exporter
